const translations = {

    en: {
        gallery: "Gallery",
        worlds: "Worlds",
        categories: "Categories",
        about: "About",
        contact: "Contact",
        exploreGallery: "EXPLORE GALLERY",
        heroEyebrow: "A GALLERY OF IMAGINED WORLDS",
        heroTitle: "PRISMA REALM",

       
	   heroText: "Light enters. Imagination emerges. Explore worlds beyond reality.",
	   exploreRealms: "EXPLORE THE REALMS",
worldsIntro: "Enter imagined worlds, each with its own landscapes, creatures, legends and stories.",
ardaWorld: "The World of Tolkien",
ardaEyebrow: "THE WORLD OF TOLKIEN",
ardaIntro: "Journey through the history of Arda, from the ancient days of the First Age to the twilight of the Third. Discover its peoples, kingdoms, heroes, creatures and legendary places.",
firstAge: "THE FIRST AGE",
firstAgeSubtitle: "The Elder Days — the beginning of the great history of Arda.",
firstAgeType: "The ancient kingdoms, heroes and wars of the Elder Days.",


eruIluvatar: "Eru Ilúvatar",
eruIluvatarDesc: "At the beginning there is Eru Ilúvatar, the Creator, origin of all that will be Arda.",
ainurSong: "The Song of the Ainur",
ainurSongDesc: "The Ainur perform the Great Music, from which the vision of the future world is born.",
ardaVision: "The Vision of Arda",
ardaVisionDesc: "The Music takes shape in the vision of Arda, the world destined to become reality.",
valarAgainstMelkor: "The Valar against Melkor",
valarAgainstMelkorDesc: "Melkor opposes the order of the other Ainur and becomes the first great force of discord.",
firstWar: "The First War",
firstWarDesc: "The Valar fight Melkor for dominion over Arda, reshaping the still-young world.",
valarDescent: "The Descent of the Valar",
valarDescentDesc: "The Valar enter Arda to shape it and prepare it for the coming of the Children of Ilúvatar.",
twoLamps: "The Two Lamps",
twoLampsDesc: "Illuin and Ormal illuminate Arda, bringing light to lands still without the Sun and the Moon.",
awakeningOfElves: "The Awakening of the Elves",
awakeningOfElvesDesc: "At Cuiviénen, the first Elves awaken, the Firstborn of Ilúvatar.",
eldar: "The Eldar",
eldarDesc: "Many Elves accept the invitation of the Valar and undertake the Great Journey westward.",
silmarilsCreation: "The Creation of the Silmarils",
silmarilsCreationDesc: "Fëanor forges the three Silmarils, capturing within them the light of the Two Trees of Valinor.",
deathOfFinwe: "The Death of Finwë",
deathOfFinweDesc: "Melkor returns to action, kills Finwë and takes the Silmarils from Fëanor's house.",
melkorUngoliant: "Melkor and Ungoliant",
melkorUngoliantDesc: "Melkor allies himself with Ungoliant, and together they bring about the death of the Two Trees of Valinor.",
silmarilsTheft: "The Theft of the Silmarils",
silmarilsTheftDesc: "After the death of Finwë, Melkor flees from Valinor carrying the Silmarils.",
feanorOath: "The Oath of Fëanor",
feanorOathDesc: "Fëanor and his sons swear to pursue anyone who possesses or takes the Silmarils.",
alqualonde: "The Kinslaying at Alqualondë",
alqualondeDesc: "The Noldor attack the Teleri to seize their ships. It is the first of the great kinslayings.",
judgmentOfMandos: "The Judgment of Mandos",
judgmentOfMandosDesc: "Mandos pronounces judgment upon the Noldor and the consequences of their rebellion.",
sunAndMoon: "The Sun and the Moon",
sunAndMoonDesc: "After the destruction of the Trees, the Sun and the Moon finally rise in the skies of Arda.",
helcaraxe: "Across the Helcaraxë",
helcaraxeDesc: "Fingolfin and his followers endure the terrible crossing of the Grinding Ice to reach Middle-earth.",
beleriand: "Beleriand",
beleriandDesc: "The Noldor arrive in Beleriand, and new Elven kingdoms arise, destined to become the heart of the First Age.",
morgothRegroups: "Morgoth Regroups",
morgothRegroupsDesc: "In the north, Morgoth rebuilds Angband and gathers the forces that will soon threaten all the kingdoms of Beleriand.",
dagorNuinGiliath: "The Dagor-nuin-Giliath",
dagorNuinGiliathDesc: "The Noldor face the armies of Morgoth in the first great battle after their return to Middle-earth.",
fallOfFingolfin: "The Fall of Fingolfin",
fallOfFingolfinDesc: "Fingolfin challenges Morgoth at the gates of Angband and fights the Dark Lord alone.",
berenMeetsLuthien: "Beren Meets Lúthien",
berenMeetsLuthienDesc: "In the forest of Doriath, Beren meets Lúthien, and one of the greatest love stories of Arda begins.",
silmaril: "The Silmaril",
silmarilDesc: "Beren tears a Silmaril from Morgoth's crown and fulfills the mission.",
berenCarcharoth: "Beren and Carcharoth",
berenCarcharothDesc: "Carcharoth swallows the Silmaril and flees through Doriath, pursued by Beren.",
silmarilRecovered: "The Silmaril Recovered",
silmarilRecoveredDesc: "The hunt for Carcharoth leads to the recovery of the Silmaril and the conclusion of the great quest of Beren and Lúthien.",
turinGlaurung: "Túrin and Glaurung",
turinGlaurungDesc: "Túrin's life becomes one of the darkest tragedies of the First Age, forever bound to the dragon Glaurung.",
fallOfNargothrond: "The Fall of Nargothrond",
fallOfNargothrondDesc: "Glaurung leads Morgoth's armies to the destruction of the great underground kingdom.",
fallOfGondolin: "The Fall of Gondolin",
fallOfGondolinDesc: "Turgon's hidden kingdom is discovered and destroyed by the forces of Morgoth.",
escapeFromGondolin: "The Escape from Gondolin",
escapeFromGondolinDesc: "Tuor, Idril and the survivors escape the ruined city and reach the mouths of the Sirion.",
earendilElwing: "Eärendil and Elwing",
earendilElwingDesc: "At the mouths of the Sirion, the fates of the last great kindreds of Elves and Men become intertwined.",
elwingReachesEarendil: "Elwing Reaches Eärendil",
elwingReachesEarendilDesc: "Elwing reaches Eärendil carrying the Silmaril, after the destruction of the havens of the Sirion.",
earendilJourney: "The Voyage of Eärendil",
earendilJourneyDesc: "Eärendil sails westward in search of the land of the Valar, carrying the Silmaril with him.",
earendilReachesAman: "Eärendil Reaches Aman",
earendilReachesAmanDesc: "After the long voyage across the western seas, Eärendil reaches the shores of Aman.",
pleaToValar: "The Plea to the Valar",
pleaToValarDesc: "Eärendil brings the Valar the plea for help from Elves and Men against Morgoth.",
vingilot: "Vingilot",
vingilotDesc: "Eärendil becomes the bearer of the Silmaril in the heavens, a symbol of hope for those who still fight against Morgoth.",
lastChildren: "The Last Children of the Great Kindreds",
lastChildrenDesc: "The events of the First Age leave a legacy destined to survive into the Ages that follow.",
finalConfrontationPreparation: "The Preparation for the Final Battle",
finalConfrontationPreparationDesc: "Morgoth gathers his remaining great forces to face the army of the Valar.",
morgothArmy: "Morgoth's Army",
morgothArmyDesc: "Orcs, Balrogs, dragons and other dark creatures are assembled for the decisive battle.",
warOfWrath: "The War of Wrath",
warOfWrathDesc: "The armies of the West arrive in Middle-earth, and the war that will end Morgoth's dominion begins.",
fallOfAncalagon: "The Fall of Ancalagon",
fallOfAncalagonDesc: "Eärendil confronts Ancalagon the Black in the skies, contributing to the final defeat of Morgoth's forces.",
captureOfMorgoth: "The Capture of Morgoth",
captureOfMorgothDesc: "After his defeat, Morgoth is captured by the forces of the Valar and stripped of his power.",
morgothDefeated: "Morgoth Defeated",
morgothDefeatedDesc: "The War of Wrath ends with the defeat of Morgoth and the fall of his dominion.",
morgothCrown: "The Crown of Morgoth",
morgothCrownDesc: "The crown that once held the Silmarils remains as a testament to the great fall of the Dark Lord.",
gatesOfVoid: "At the Gates of the Void",
gatesOfVoidDesc: "Morgoth is brought before the threshold beyond which he will be banished forever.",
morgothInVoid: "Morgoth in the Void",
morgothInVoidDesc: "Morgoth is cast beyond the Walls of the World, and his presence in Arda comes to an end.",
endOfBeleriand: "The End of Beleriand",
endOfBeleriandDesc: "The War of Wrath devastates the continent: much of Beleriand sinks beneath the sea, and the First Age comes to an end.",



secondAge: "THE SECOND AGE",


secondAge: "THE SECOND AGE",
secondAgeType: "The rise and fall of kingdoms, Númenor and the forging of the Rings.",
thirdAge: "THE THIRD AGE",
thirdAgeType: "The age of the great kingdoms and the War of the Ring.",
ardaCharacters: "CHARACTERS",
ardaCharactersType: "Heroes, kings, elves, warriors, creatures and legendary figures.",
ardaPlaces: "PLACES",
ardaPlacesType: "Kingdoms, cities, forests, mountains and forgotten lands.",
ardaCreatures: "CREATURES",
ardaCreaturesType: "Beasts, monsters and beings that inhabit the world of Arda.",
eternalKingdoms: "THE ETERNAL KINGDOMS",
eternalKingdomsType: "Realms of kings, castles and ancient powers",
wildlands: "THE WILDLANDS",
wildlandsType: "Untamed landscapes and forgotten places",
darkRealms: "THE DARK REALMS",
darkRealmsType: "Shadowed lands, ruins and forbidden kingdoms",
celestialRealms: "THE CELESTIAL REALMS",
celestialRealmsType: "Worlds beyond the boundaries of reality",
forgottenLands: "THE FORGOTTEN LANDS",
forgottenLandsType: "Lost civilizations and mysteries of the past",
	   
latestArtworks: "LATEST ARTWORKS",
lostValley: "THE LOST VALLEY",
dragonOfAsh: "DRAGON OF ASH",
dragonType: "Fantasy · Creature",
citadelInClouds: "CITADEL IN THE CLOUDS",
citadelType: "Fantasy · Environment",
landscapes: "LANDSCAPES",
landscapesType: "Places and horizons",
ancientForest: "ANCIENT FOREST",
landscapeType: "Fantasy · Landscape",
fallenKing: "THE FALLEN KING",
fallenKingType: "Dark Fantasy · Character",
shatteredRealm: "SHATTERED REALM",
shatteredRealmType: "Dark Fantasy · Environment",
fantasy: "FANTASY",
fantasyType: "Epic worlds and legends",
creatures: "CREATURES",
creaturesType: "Beasts and beings",
worlds: "WORLDS",
worldsType: "Realms and dimensions",
characters: "CHARACTERS",
charactersType: "Heroes and villains",
darkFantasy: "DARK FANTASY",
darkFantasyType: "Shadows and corruption",
exploreCategories: "EXPLORE CATEGORIES",
whereImaginationTakesForm: "WHERE IMAGINATION TAKES FORM",
navigation: "NAVIGATION",
info: "INFO",
termsOfUse: "Terms of Use",
privacyPolicy: "Privacy Policy",
cookiesPolicy: "Cookies Policy",
stayUpdated: "STAY UPDATED",
newArtworks: "New artworks, behind the scenes and exclusive content.",
emailPlaceholder: "Your email address"
	},

    it: {
        gallery: "Galleria",
        worlds: "Mondi",
        categories: "Categorie",
        about: "Chi siamo",
        contact: "Contatti",
        exploreGallery: "ESPLORA LA GALLERIA",
        heroEyebrow: "UNA GALLERIA DI MONDI IMMAGINARI",
        heroTitle: "PRISMA REALM",

        heroText: "La luce entra. L'immaginazione emerge. Esplora mondi oltre la realtà.",
exploreRealms: "ESPLORA I REGNI",
worldsIntro: "Entra in mondi immaginari, ognuno con i propri paesaggi, creature, leggende e storie.",
ardaWorld: "Il Mondo di Tolkien",
ardaEyebrow: "IL MONDO DI TOLKIEN",
ardaIntro: "Viaggia attraverso la storia di Arda, dagli antichi giorni della Prima Era fino al crepuscolo della Terza. Scopri i suoi popoli, regni, eroi, creature e luoghi leggendari.",
firstAge: "LA PRIMA ERA",
firstAgeSubtitle: "I Giorni Antichi — l'inizio della grande storia di Arda.",
firstAgeType: "Gli antichi regni, gli eroi e le guerre dei Giorni Antichi.",

eruIluvatar: "Eru Ilúvatar",
eruIluvatarDesc: "All'inizio esiste Eru Ilúvatar, il Creatore, origine di tutto ciò che sarà Arda.",
ainurSong: "Il Canto degli Ainur",
ainurSongDesc: "Gli Ainur intonano la Grande Musica, dalla quale nasce la visione del mondo futuro.",
ardaVision: "La visione di Arda",
ardaVisionDesc: "La Musica prende forma nella visione di Arda, il mondo destinato a diventare realtà.",
valarAgainstMelkor: "I Valar contro Melkor",
valarAgainstMelkorDesc: "Melkor si oppone all'ordine degli altri Ainur e diventa la prima grande forza di discordia.",
firstWar: "La prima guerra",
firstWarDesc: "I Valar combattono Melkor per il dominio di Arda, sconvolgendo il mondo ancora giovane.",
valarDescent: "La discesa dei Valar",
valarDescentDesc: "I Valar entrano in Arda per plasmarla e prepararla alla venuta dei Figli di Ilúvatar.",
twoLamps: "Le Due Lampade",
twoLampsDesc: "Illuin e Ormal illuminano Arda, portando luce nelle terre ancora prive del Sole e della Luna.",
awakeningOfElves: "Il risveglio degli Elfi",
awakeningOfElvesDesc: "A Cuiviénen si risvegliano i primi Elfi, i Primogeniti di Ilúvatar.",
eldar: "Gli Eldar",
eldarDesc: "Molti Elfi accettano l'invito dei Valar e intraprendono la Grande Marcia verso Occidente.",
silmarilsCreation: "La creazione dei Silmaril",
silmarilsCreationDesc: "Fëanor forgia i tre Silmaril, racchiudendo in essi la luce dei Due Alberi di Valinor.",
deathOfFinwe: "La morte di Finwë",
deathOfFinweDesc: "Melkor torna in azione, uccide Finwë e sottrae i Silmaril dalla casa di Fëanor.",
melkorUngoliant: "Melkor e Ungoliant",
melkorUngoliantDesc: "Melkor si allea con Ungoliant, che insieme causano la morte dei Due Alberi di Valinor.",
silmarilsTheft: "Il furto dei Silmaril",
silmarilsTheftDesc: "Dopo la morte di Finwë, Melkor fugge da Valinor portando con sé i Silmaril.",
feanorOath: "Il Giuramento di Fëanor",
feanorOathDesc: "Fëanor e i suoi figli giurano di perseguire chiunque possieda o sottragga i Silmaril.",
alqualonde: "La strage di Alqualondë",
alqualondeDesc: "I Noldor attaccano i Teleri per impossessarsi delle loro navi. È il primo dei grandi massacri fratricidi.",
judgmentOfMandos: "Il Giudizio di Mandos",
judgmentOfMandosDesc: "Mandos pronuncia il giudizio sui Noldor e sulle conseguenze della loro ribellione.",
sunAndMoon: "Il Sole e la Luna",
sunAndMoonDesc: "Dopo la distruzione degli Alberi, il Sole e la Luna sorgono finalmente nei cieli di Arda.", 
helcaraxe: "Attraverso il Helcaraxë",
helcaraxeDesc: "Fingolfin e i suoi seguaci affrontano il terribile passaggio del Ghiaccio Macinatore per raggiungere la Terra di Mezzo.",
beleriand: "Il Beleriand",
beleriandDesc: "I Noldor giungono nel Beleriand e sorgono nuovi regni elfici destinati a diventare il cuore della Prima Era.",
morgothRegroups: "Morgoth si riorganizza",
morgothRegroupsDesc: "Nel nord, Morgoth ricostruisce Angband e raduna le forze che presto minacceranno tutti i regni del Beleriand.",
dagorNuinGiliath: "La Dagor-nuin-Giliath",
dagorNuinGiliathDesc: "I Noldor affrontano gli eserciti di Morgoth nella prima grande battaglia dopo il loro ritorno nella Terra di Mezzo.",
fallOfFingolfin: "La caduta di Fingolfin",
fallOfFingolfinDesc: "Fingolfin sfida Morgoth alle porte di Angband e combatte da solo contro il Signore Oscuro.",
berenMeetsLuthien: "Beren incontra Lúthien",
berenMeetsLuthienDesc: "Nella foresta di Doriath, Beren incontra Lúthien e ha inizio una delle più grandi storie d'amore di Arda.",
silmaril: "Il Silmaril",
silmarilDesc: "Beren strappa un Silmaril dalla corona di Morgoth e porta a compimento la missione.",
berenCarcharoth: "Beren e Carcharoth",
berenCarcharothDesc: "Carcharoth inghiotte il Silmaril e fugge attraverso Doriath, inseguito da Beren.",
silmarilRecovered: "Il Silmaril recuperato",
silmarilRecoveredDesc: "La caccia a Carcharoth conduce alla riconquista del Silmaril e alla conclusione della grande impresa di Beren e Lúthien.",
turinGlaurung: "Túrin e Glaurung",
turinGlaurungDesc: "La vita di Túrin diventa una delle più oscure tragedie della Prima Era, legata indissolubilmente al drago Glaurung.",
fallOfNargothrond: "La caduta di Nargothrond",
fallOfNargothrondDesc: "Glaurung conduce gli eserciti di Morgoth alla distruzione del grande regno sotterraneo.",
fallOfGondolin: "La caduta di Gondolin",
fallOfGondolinDesc: "Il regno nascosto di Turgon viene scoperto e distrutto dalle forze di Morgoth.",
escapeFromGondolin: "La fuga da Gondolin",
escapeFromGondolinDesc: "Tuor, Idril e i superstiti riescono a fuggire dalla città in rovina e a raggiungere le foci del Sirion.",
earendilElwing: "Eärendil ed Elwing",
earendilElwingDesc: "Alle foci del Sirion si intrecciano le vicende delle ultime grandi stirpi degli Elfi e degli Uomini.",
elwingReachesEarendil: "Elwing raggiunge Eärendil",
elwingReachesEarendilDesc: "Elwing raggiunge Eärendil portando il Silmaril, dopo la distruzione dei rifugi del Sirion.", 
earendilJourney: "Il viaggio di Eärendil",
earendilJourneyDesc: "Eärendil naviga verso Occidente alla ricerca della terra dei Valar, portando con sé il Silmaril.",
earendilReachesAman: "Eärendil raggiunge Aman",
earendilReachesAmanDesc: "Dopo il lungo viaggio attraverso i mari dell'Occidente, Eärendil raggiunge le coste di Aman.",
pleaToValar: "La supplica ai Valar",
pleaToValarDesc: "Eärendil porta ai Valar la richiesta di aiuto degli Elfi e degli Uomini contro Morgoth.",
vingilot: "Vingilot",
vingilotDesc: "Eärendil diventa il portatore del Silmaril nei cieli, simbolo di speranza per coloro che ancora combattono contro Morgoth.",
lastChildren: "Gli ultimi figli delle grandi stirpi",
lastChildrenDesc: "Le vicende della Prima Era lasciano un'eredità destinata a sopravvivere nelle Ere successive.",
finalConfrontationPreparation: "La preparazione dello scontro finale",
finalConfrontationPreparationDesc: "Morgoth raccoglie le sue ultime grandi forze per affrontare l'esercito dei Valar.",
morgothArmy: "L'esercito di Morgoth",
morgothArmyDesc: "Orchi, Balrog, draghi e altre creature oscure vengono schierati per la battaglia decisiva.",
warOfWrath: "La Guerra dell'Ira",
warOfWrathDesc: "Gli eserciti dell'Occidente giungono nella Terra di Mezzo e ha inizio la guerra che porrà fine al dominio di Morgoth.",
fallOfAncalagon: "La caduta di Ancalagon",
fallOfAncalagonDesc: "Eärendil affronta Ancalagon il Nero nei cieli e contribuisce alla definitiva sconfitta delle forze di Morgoth.",
captureOfMorgoth: "La cattura di Morgoth",
captureOfMorgothDesc: "Dopo la sconfitta, Morgoth viene catturato dalle forze dei Valar e privato del suo potere.",
morgothDefeated: "Morgoth sconfitto",
morgothDefeatedDesc: "La Guerra dell'Ira termina con la sconfitta di Morgoth e la caduta del suo dominio.",
morgothCrown: "La corona di Morgoth",
morgothCrownDesc: "La corona che aveva contenuto i Silmaril rimane come testimonianza della grande caduta del Signore Oscuro.",
gatesOfVoid: "Alle porte del Vuoto",
gatesOfVoidDesc: "Morgoth viene condotto davanti alla soglia oltre la quale sarà bandito per sempre.",
morgothInVoid: "Morgoth nel Vuoto",
morgothInVoidDesc: "Morgoth viene espulso oltre le mura del mondo e la sua presenza in Arda giunge alla fine.",
endOfBeleriand: "La fine del Beleriand",
endOfBeleriandDesc: "La Guerra dell'Ira sconvolge il continente: gran parte del Beleriand sprofonda nelle acque e la Prima Era giunge al termine.",
  
  
secondAge: "LA SECONDA ERA",

 
secondAgeType: "L'ascesa e la caduta dei regni, Númenor e la forgiatura degli Anelli.",
thirdAge: "LA TERZA ERA",
thirdAgeType: "L'epoca dei grandi regni e della Guerra dell'Anello.",
ardaCharacters: "PERSONAGGI",
ardaCharactersType: "Eroi, re, elfi, guerrieri, creature e figure leggendarie.",
ardaPlaces: "LUOGHI",
ardaPlacesType: "Regni, città, foreste, montagne e terre dimenticate.",
ardaCreatures: "CREATURE",
ardaCreaturesType: "Bestie, mostri ed esseri che abitano il mondo di Arda.",
eternalKingdoms: "I REGNI ETERNI",
eternalKingdomsType: "Regni di re, castelli e antichi poteri",
wildlands: "LE TERRE SELVAGGE",
wildlandsType: "Paesaggi incontaminati e luoghi dimenticati",
darkRealms: "I REGNI OSCURI",
darkRealmsType: "Terre nell'ombra, rovine e regni proibiti",
celestialRealms: "I REGNI CELESTIALI",
celestialRealmsType: "Mondi oltre i confini della realtà",
forgottenLands: "LE TERRE DIMENTICATE",
forgottenLandsType: "Civiltà perdute e misteri del passato",
latestArtworks: "ULTIME OPERE",
lostValley: "LA VALLE PERDUTA",
dragonOfAsh: "DRAGO DI CENERE",
dragonType: "Fantasy · Creatura",
citadelInClouds: "CITTÀ DELLE NUVOLE",
citadelType: "Fantasy · Ambientazione",
landscapes: "PAESAGGI",
landscapesType: "Luoghi e orizzonti",
ancientForest: "FORESTA ANTICA",
landscapeType: "Fantasy · Paesaggio",
fallenKing: "IL RE CADUTO",
fallenKingType: "Dark Fantasy · Personaggio",
shatteredRealm: "REGNO FRANTUMATO",
shatteredRealmType: "Dark Fantasy · Ambientazione",
fantasy: "FANTASY",
fantasyType: "Mondi epici e leggende",
creatures: "CREATURE",
creaturesType: "Bestie ed esseri",
worlds: "MONDI",
worldsType: "Regni e dimensioni",
characters: "PERSONAGGI",
charactersType: "Eroi e malvagi",
darkFantasy: "DARK FANTASY",
darkFantasyType: "Ombre e corruzione",
exploreCategories: "ESPLORA CATEGORIE",
whereImaginationTakesForm: "DOVE L'IMMAGINAZIONE PRENDE FORMA",
navigation: "NAVIGAZIONE",
info: "INFO",
termsOfUse: "Termini di utilizzo",
privacyPolicy: "Informativa sulla privacy",
cookiesPolicy: "Politica sui cookie",
stayUpdated: "RESTA AGGIORNATO",
newArtworks: "Nuove opere, dietro le quinte e contenuti esclusivi.",
emailPlaceholder: "Il tuo indirizzo email"
	}

};


function setLanguage(lang) {

    const languageButton = document.getElementById("language-toggle");

    if (languageButton) {
        languageButton.textContent = lang.toUpperCase();
    }

    document.querySelectorAll("[data-i18n]").forEach(element => {

        const key = element.getAttribute("data-i18n");

        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }

    });

    document.documentElement.classList.add("language-ready");

    localStorage.setItem("prismaLanguage", lang);
}


function toggleLanguage() {
    const currentLanguage = localStorage.getItem("prismaLanguage") || "en";
    setLanguage(currentLanguage === "en" ? "it" : "en");
}


document.addEventListener("DOMContentLoaded", () => {

    const savedLanguage = localStorage.getItem("prismaLanguage") || "en";

    setLanguage(savedLanguage);


});