const translations = {

    en: {
        gallery: "Gallery",
        worlds: "Worlds",
        categories: "Categories",
        about: "About",
        contact: "Contact",
        exploreGallery: "EXPLORE GALLERY",
        heroEyebrow: "A GALLERY OF IMAGINED WORLDS",
        heroTitle: "PRISMA REALM",

       
	   heroText: "Light enters. Imagination emerges. Explore worlds beyond reality.",
	   exploreRealms: "EXPLORE THE REALMS",
worldsIntro: "Enter imagined worlds, each with its own landscapes, creatures, legends and stories.",
ardaWorld: "The World of Tolkien",
ardaEyebrow: "THE WORLD OF TOLKIEN",
ardaIntro: "Journey through the history of Arda, from the ancient days of the First Age to the twilight of the Third. Discover its peoples, kingdoms, heroes, creatures and legendary places.",
firstAge: "THE FIRST AGE",
firstAgeSubtitle: "The Elder Days — the beginning of the great history of Arda.",
firstAgeType: "The ancient kingdoms, heroes and wars of the Elder Days.",


eruIluvatar: "Eru Ilúvatar",
eruIluvatarDesc: "At the beginning there is Eru Ilúvatar, the Creator, origin of all that will be Arda.",
ainurSong: "The Song of the Ainur",
ainurSongDesc: "The Ainur perform the Great Music, from which the vision of the future world is born.",
ardaVision: "The Vision of Arda",
ardaVisionDesc: "The Music takes shape in the vision of Arda, the world destined to become reality.",
valarAgainstMelkor: "The Valar against Melkor",
valarAgainstMelkorDesc: "Melkor opposes the order of the other Ainur and becomes the first great force of discord.",
firstWar: "The First War",
firstWarDesc: "The Valar fight Melkor for dominion over Arda, reshaping the still-young world.",
valarDescent: "The Descent of the Valar",
valarDescentDesc: "The Valar enter Arda to shape it and prepare it for the coming of the Children of Ilúvatar.",
twoLamps: "The Two Lamps",
twoLampsDesc: "Illuin and Ormal illuminate Arda, bringing light to lands still without the Sun and the Moon.",
awakeningOfElves: "The Awakening of the Elves",
awakeningOfElvesDesc: "At Cuiviénen, the first Elves awaken, the Firstborn of Ilúvatar.",
eldar: "The Eldar",
eldarDesc: "Many Elves accept the invitation of the Valar and undertake the Great Journey westward.",
silmarilsCreation: "The Creation of the Silmarils",
silmarilsCreationDesc: "Fëanor forges the three Silmarils, capturing within them the light of the Two Trees of Valinor.",
deathOfFinwe: "The Death of Finwë",
deathOfFinweDesc: "Melkor returns to action, kills Finwë and takes the Silmarils from Fëanor's house.",
melkorUngoliant: "Melkor and Ungoliant",
melkorUngoliantDesc: "Melkor allies himself with Ungoliant, and together they bring about the death of the Two Trees of Valinor.",
silmarilsTheft: "The Theft of the Silmarils",
silmarilsTheftDesc: "After the death of Finwë, Melkor flees from Valinor carrying the Silmarils.",
feanorOath: "The Oath of Fëanor",
feanorOathDesc: "Fëanor and his sons swear to pursue anyone who possesses or takes the Silmarils.",
alqualonde: "The Kinslaying at Alqualondë",
alqualondeDesc: "The Noldor attack the Teleri to seize their ships. It is the first of the great kinslayings.",
judgmentOfMandos: "The Judgment of Mandos",
judgmentOfMandosDesc: "Mandos pronounces judgment upon the Noldor and the consequences of their rebellion.",
sunAndMoon: "The Sun and the Moon",
sunAndMoonDesc: "After the destruction of the Trees, the Sun and the Moon finally rise in the skies of Arda.",
helcaraxe: "Across the Helcaraxë",
helcaraxeDesc: "Fingolfin and his followers endure the terrible crossing of the Grinding Ice to reach Middle-earth.",
beleriand: "Beleriand",
beleriandDesc: "The Noldor arrive in Beleriand, and new Elven kingdoms arise, destined to become the heart of the First Age.",
morgothRegroups: "Morgoth Regroups",
morgothRegroupsDesc: "In the north, Morgoth rebuilds Angband and gathers the forces that will soon threaten all the kingdoms of Beleriand.",
dagorNuinGiliath: "The Dagor-nuin-Giliath",
dagorNuinGiliathDesc: "The Noldor face the armies of Morgoth in the first great battle after their return to Middle-earth.",
fallOfFingolfin: "The Fall of Fingolfin",
fallOfFingolfinDesc: "Fingolfin challenges Morgoth at the gates of Angband and fights the Dark Lord alone.",
berenMeetsLuthien: "Beren Meets Lúthien",
berenMeetsLuthienDesc: "In the forest of Doriath, Beren meets Lúthien, and one of the greatest love stories of Arda begins.",
silmaril: "The Silmaril",
silmarilDesc: "Beren tears a Silmaril from Morgoth's crown and fulfills the mission.",
berenCarcharoth: "Beren and Carcharoth",
berenCarcharothDesc: "Carcharoth swallows the Silmaril and flees through Doriath, pursued by Beren.",
silmarilRecovered: "The Silmaril Recovered",
silmarilRecoveredDesc: "The hunt for Carcharoth leads to the recovery of the Silmaril and the conclusion of the great quest of Beren and Lúthien.",
turinGlaurung: "Túrin and Glaurung",
turinGlaurungDesc: "Túrin's life becomes one of the darkest tragedies of the First Age, forever bound to the dragon Glaurung.",
fallOfNargothrond: "The Fall of Nargothrond",
fallOfNargothrondDesc: "Glaurung leads Morgoth's armies to the destruction of the great underground kingdom.",
fallOfGondolin: "The Fall of Gondolin",
fallOfGondolinDesc: "Turgon's hidden kingdom is discovered and destroyed by the forces of Morgoth.",
escapeFromGondolin: "The Escape from Gondolin",
escapeFromGondolinDesc: "Tuor, Idril and the survivors escape the ruined city and reach the mouths of the Sirion.",
earendilElwing: "Eärendil and Elwing",
earendilElwingDesc: "At the mouths of the Sirion, the fates of the last great kindreds of Elves and Men become intertwined.",
elwingReachesEarendil: "Elwing Reaches Eärendil",
elwingReachesEarendilDesc: "Elwing reaches Eärendil carrying the Silmaril, after the destruction of the havens of the Sirion.",
earendilJourney: "The Voyage of Eärendil",
earendilJourneyDesc: "Eärendil sails westward in search of the land of the Valar, carrying the Silmaril with him.",
earendilReachesAman: "Eärendil Reaches Aman",
earendilReachesAmanDesc: "After the long voyage across the western seas, Eärendil reaches the shores of Aman.",
pleaToValar: "The Plea to the Valar",
pleaToValarDesc: "Eärendil brings the Valar the plea for help from Elves and Men against Morgoth.",
vingilot: "Vingilot",
vingilotDesc: "Eärendil becomes the bearer of the Silmaril in the heavens, a symbol of hope for those who still fight against Morgoth.",
lastChildren: "The Last Children of the Great Kindreds",
lastChildrenDesc: "The events of the First Age leave a legacy destined to survive into the Ages that follow.",
finalConfrontationPreparation: "The Preparation for the Final Battle",
finalConfrontationPreparationDesc: "Morgoth gathers his remaining great forces to face the army of the Valar.",
morgothArmy: "Morgoth's Army",
morgothArmyDesc: "Orcs, Balrogs, dragons and other dark creatures are assembled for the decisive battle.",
warOfWrath: "The War of Wrath",
warOfWrathDesc: "The armies of the West arrive in Middle-earth, and the war that will end Morgoth's dominion begins.",
fallOfAncalagon: "The Fall of Ancalagon",
fallOfAncalagonDesc: "Eärendil confronts Ancalagon the Black in the skies, contributing to the final defeat of Morgoth's forces.",
captureOfMorgoth: "The Capture of Morgoth",
captureOfMorgothDesc: "After his defeat, Morgoth is captured by the forces of the Valar and stripped of his power.",
morgothDefeated: "Morgoth Defeated",
morgothDefeatedDesc: "The War of Wrath ends with the defeat of Morgoth and the fall of his dominion.",
morgothCrown: "The Crown of Morgoth",
morgothCrownDesc: "The crown that once held the Silmarils remains as a testament to the great fall of the Dark Lord.",
gatesOfVoid: "At the Gates of the Void",
gatesOfVoidDesc: "Morgoth is brought before the threshold beyond which he will be banished forever.",
morgothInVoid: "Morgoth in the Void",
morgothInVoidDesc: "Morgoth is cast beyond the Walls of the World, and his presence in Arda comes to an end.",
endOfBeleriand: "The End of Beleriand",
endOfBeleriandDesc: "The War of Wrath devastates the continent: much of Beleriand sinks beneath the sea, and the First Age comes to an end.",



secondAge: "THE SECOND AGE",


secondAge: "THE SECOND AGE",
secondAgeType: "The rise and fall of kingdoms, Númenor and the forging of the Rings.",
        secondAgeSubtitle: "The rise and fall of kingdoms, Númenor and the forging of the Rings.",
        saTitle1: "Lindon and the Grey Havens",
        saDesc1: "Lindon and the western havens of the Elves become the center of Elven presence in Middle-earth.",
        saTitle2: "Númenor",
        saDesc2: "The island of Númenor becomes the great homeland of the Edain, at the heart of the Second Age.",
        saTitle3: "The Expansion of Númenor",
        saDesc3: "The Númenóreans expand their influence along the coasts of Middle-earth.",
        saTitle4: "Sauron's Return to Middle-earth",
        saDesc4: "Sauron returns to Middle-earth and begins once again to gather power and servants.",
        saTitle5: "Eregion",
        saDesc5: "The Elves found Eregion near the Misty Mountains, turning it into a great center of craft and smithing.",
        saTitle6: "Annatar and Celebrimbor",
        saDesc6: "Sauron, in the guise of Annatar, presents himself to the Elves and gains Celebrimbor's trust.",
        saTitle7: "The Rings of Power",
        saDesc7: "The smiths of Eregion forge the Rings of Power under the influence of Annatar's teachings.",
        saTitle8: "The Elven Rings",
        saDesc8: "Celebrimbor and the Elven-smiths create the Three Rings, meant to preserve and protect what is beautiful in Middle-earth.",
        saTitle9: "The Giving of the Elven Rings",
        saDesc9: "The Three Rings are entrusted to the great Elven lords and kept beyond Sauron's direct influence.",
        saTitle10: "Sauron Forges the One",
        saDesc10: "Sauron forges the One Ring to dominate the other Rings of Power and their bearers.",
        saTitle11: "The Invasion of Eriador",
        saDesc11: "Sauron's armies invade Eriador and advance against the realms of the Elves.",
        saTitle12: "The End of Eregion",
        saDesc12: "Eregion is devastated and Celebrimbor is killed; the region forever loses its role as a great Elven center.",
        saTitle13: "Sauron Takes the Nine Rings",
        saDesc13: "Sauron takes possession of the Nine Rings destined for Men.",
        saTitle14: "Retreat to Mordor",
        saDesc14: "After the war, Sauron once again concentrates his power in the lands of Mordor.",
        saTitle15: "The Giving of the Nine",
        saDesc15: "Sauron gives the Nine Rings to powerful Men, who in time become the Nazgûl.",
        saTitle16: "Númenóreans Aid the Elves",
        saDesc16: "The great fleet of Númenor arrives in Middle-earth and forces Sauron to retreat.",
        saTitle17: "Númenórean Expansion",
        saDesc17: "The Númenóreans consolidate their presence along the coasts of Middle-earth and found new settlements.",
        saTitle18: "Sauron Conquers Some Settlements",
        saDesc18: "Sauron's influence grows in Middle-earth, threatening Númenórean dominions.",
        saTitle19: "Umbar",
        saDesc19: "Umbar becomes one of the great strongholds and naval bases of the Númenóreans in Middle-earth.",
        saTitle20: "Pelargir",
        saDesc20: "Pelargir is founded as a great haven of the Faithful Númenóreans on the banks of the Anduin.",
        saTitle21: "Ar-Pharazôn",
        saDesc21: "Ar-Pharazôn ascends the throne of Númenor and becomes the most powerful of the island's kings.",
        saTitle22: "Ar-Pharazôn Hears of Sauron",
        saDesc22: "Ar-Pharazôn learns of the growing threat of Sauron and decides to confront him.",
        saTitle23: "Ar-Pharazôn Prepares His Army",
        saDesc23: "The King of Númenor prepares a great army to subdue Sauron.",
        saTitle24: "Sauron and Ar-Pharazôn",
        saDesc24: "Ar-Pharazôn arrives in Middle-earth and Sauron realizes he cannot defeat him by force.",
        saTitle25: "Sauron Surrenders to Ar-Pharazôn",
        saDesc25: "Sauron willingly chooses to surrender and allows himself to be taken prisoner to Númenor.",
        saTitle26: "Sauron Is Taken to Númenor",
        saDesc26: "Sauron is brought to the island as a prisoner, but quickly begins to prepare his revenge.",
        saTitle27: "Sauron's Corruption",
        saDesc27: "Sauron gains Ar-Pharazôn's trust and begins to corrupt the court and society of Númenor.",
        saTitle28: "Ar-Pharazôn Against the Valar",
        saDesc28: "Sauron convinces Ar-Pharazôn that death is a deception and drives him against Aman.",
        saTitle29: "Tensions in Númenor",
        saDesc29: "The divide grows within Númenor between the Faithful to the Valar and those who desire greater power and dominion.",
        saTitle30: "Amandil's Decision",
        saDesc30: "Amandil, father of Elendil, decides to make a desperate voyage to Aman to ask the Valar for help.",
        saTitle31: "Elendil Prepares the Expedition",
        saDesc31: "Elendil prepares the ships of the Faithful to flee Númenor before its inevitable downfall.",
        saTitle32: "Amandil Sails for Aman",
        saDesc32: "Amandil sails west in an attempt to reach Aman and plead for the mercy of the Valar.",
        saTitle33: "Ar-Pharazôn Sails for Aman",
        saDesc33: "Ar-Pharazôn sails for Aman with the Great Armament to obtain immortality.",
        saTitle34: "Ar-Pharazôn on the Shores of Aman",
        saDesc34: "Ar-Pharazôn's fleet reaches the shores of Aman, crossing the forbidden boundary.",
        saTitle35: "Manwë Turns to Eru",
        saDesc35: "Faced with the rebellion of Men, Manwë calls upon Eru Ilúvatar and entrusts Arda's fate to him.",
        saTitle36: "Eru Removes Aman",
        saDesc36: "Eru intervenes in the history of Arda and changes its structure, removing Aman from the world.",
        saTitle37: "The Destruction of Númenor",
        saDesc37: "Númenor is drowned and destroyed; Elendil and the Faithful sail toward Middle-earth.",
        saTitle38: "Sauron Is Destroyed",
        saDesc38: "The destruction of Númenor destroys Sauron's body, but not his spirit: the One Ring remains with him.",
        saTitle39: "Sauron Returns to Mordor in Spirit",
        saDesc39: "Sauron returns to Mordor in spirit and regroups.",
        saTitle40: "Sauron's New Body",
        saDesc40: "In time, Sauron manages to rebuild a physical form, no longer able to regain his original appearance.",
        saTitle41: "Map of Elendil's Expedition",
        saDesc41: "The Faithful divide: Elendil sails north, while Isildur and Anárion sail south toward the Anduin.",
        saTitle42: "The Men of the Mountains",
        saDesc42: "The Faithful divide: Elendil sails north, while Isildur and Anárion sail south toward the Anduin.",
        saTitle43: "The Founding of Arnor",
        saDesc43: "Elendil founds Arnor in the north and establishes the realm of the northern Dúnedain.",
        saTitle44: "The Founding of Gondor",
        saDesc44: "Isildur and Anárion found Gondor in the south.",
        saTitle45: "The Oath to Isildur",
        saDesc45: "The King of the Men of the Mountains swears allegiance to Isildur at the Stone of Erech.",
        saTitle46: "Gil-galad and Elendil Against Sauron",
        saDesc46: "Gil-galad and Elendil face Sauron directly in the final confrontation.",
        saTitle47: "Sauron Conquers Minas Ithil",
        saDesc47: "Sauron attacks Gondor and captures Minas Ithil, later renamed Minas Morgul.",
        saTitle48: "Isildur's Curse",
        saDesc48: "Sauron attacks Gondor and captures Minas Ithil, later renamed Minas Morgul.",
        saTitle49: "The Alliance at Imladris",
        saDesc49: "Elves and Dúnedain join the Last Alliance, while the allied forces gather at Imladris.",
        saTitle50: "The Battle of Dagorlad",
        saDesc50: "The Last Alliance faces Sauron's forces in the great Battle of Dagorlad and wins.",
        saTitle51: "The Alliance Marches to Barad-dûr",
        saDesc51: "The army of the Last Alliance crosses Middle-earth and marches toward Mordor.",
        saTitle52: "The Siege of Barad-dûr",
        saDesc52: "After the victory at Dagorlad, the forces of the Alliance enter Mordor and besiege Barad-dûr for seven years.",
        saTitle53: "Sauron Against Gil-galad and Elendil",
        saDesc53: "In the final confrontation, Sauron faces Gil-galad and Elendil and kills both Kings.",
        saTitle54: "Isildur Defeats Sauron",
        saDesc54: "Isildur cuts the Ring from Sauron's hand with the shard of Narsil's hilt and takes the One Ring.",
        saTitle55: "The Destruction of Sauron",
        saDesc55: "Separated from the One Ring, Sauron loses the Ring's power and his body is destroyed.",
        saTitle56: "Isildur and the One Ring",
        saDesc56: "Isildur remains in possession of the One Ring as the Second Age comes to an end.",
thirdAge: "THE THIRD AGE",
thirdAgeType: "The age of the great kingdoms and the War of the Ring.",
pageTitleThirdAge: "Prisma Realm — The Third Age",
ardaCharacters: "CHARACTERS",
ardaCharactersType: "Heroes, kings, elves, warriors, creatures and legendary figures.",
ardaPlaces: "PLACES",
ardaPlacesType: "Kingdoms, cities, forests, mountains and forgotten lands.",
ardaCreatures: "CREATURES",
ardaCreaturesType: "Beasts, monsters and beings that inhabit the world of Arda.",
eternalKingdoms: "THE ETERNAL KINGDOMS",
eternalKingdomsType: "Realms of kings, castles and ancient powers",
wildlands: "THE WILDLANDS",
wildlandsType: "Untamed landscapes and forgotten places",
darkRealms: "THE DARK REALMS",
darkRealmsType: "Shadowed lands, ruins and forbidden kingdoms",
celestialRealms: "THE CELESTIAL REALMS",
celestialRealmsType: "Worlds beyond the boundaries of reality",
forgottenLands: "THE FORGOTTEN LANDS",
forgottenLandsType: "Lost civilizations and mysteries of the past",
	   
latestArtworks: "LATEST ARTWORKS",
lostValley: "THE LOST VALLEY",
dragonOfAsh: "DRAGON OF ASH",
dragonType: "Fantasy · Creature",
citadelInClouds: "CITADEL IN THE CLOUDS",
citadelType: "Fantasy · Environment",
landscapes: "LANDSCAPES",
landscapesType: "Places and horizons",
ancientForest: "ANCIENT FOREST",
landscapeType: "Fantasy · Landscape",
fallenKing: "THE FALLEN KING",
fallenKingType: "Dark Fantasy · Character",
shatteredRealm: "SHATTERED REALM",
shatteredRealmType: "Dark Fantasy · Environment",
fantasy: "FANTASY",
fantasyType: "Epic worlds and legends",
creatures: "CREATURES",
creaturesType: "Beasts and beings",
worlds: "WORLDS",
worldsType: "Realms and dimensions",
characters: "CHARACTERS",
charactersType: "Heroes and villains",
darkFantasy: "DARK FANTASY",
darkFantasyType: "Shadows and corruption",
exploreCategories: "EXPLORE CATEGORIES",
whereImaginationTakesForm: "WHERE IMAGINATION TAKES FORM",
navigation: "NAVIGATION",
info: "INFO",
termsOfUse: "Terms of Use",
privacyPolicy: "Privacy Policy",
cookiesPolicy: "Cookies Policy",
stayUpdated: "STAY UPDATED",
newArtworks: "New artworks, behind the scenes and exclusive content.",
emailPlaceholder: "Your email address"
	},

    it: {
        gallery: "Galleria",
        worlds: "Mondi",
        categories: "Categorie",
        about: "Chi siamo",
        contact: "Contatti",
        exploreGallery: "ESPLORA LA GALLERIA",
        heroEyebrow: "UNA GALLERIA DI MONDI IMMAGINARI",
        heroTitle: "PRISMA REALM",

        heroText: "La luce entra. L'immaginazione emerge. Esplora mondi oltre la realtà.",
exploreRealms: "ESPLORA I REGNI",
worldsIntro: "Entra in mondi immaginari, ognuno con i propri paesaggi, creature, leggende e storie.",
ardaWorld: "Il Mondo di Tolkien",
ardaEyebrow: "IL MONDO DI TOLKIEN",
ardaIntro: "Viaggia attraverso la storia di Arda, dagli antichi giorni della Prima Era fino al crepuscolo della Terza. Scopri i suoi popoli, regni, eroi, creature e luoghi leggendari.",
firstAge: "LA PRIMA ERA",
firstAgeSubtitle: "I Giorni Antichi — l'inizio della grande storia di Arda.",
firstAgeType: "Gli antichi regni, gli eroi e le guerre dei Giorni Antichi.",

eruIluvatar: "Eru Ilúvatar",
eruIluvatarDesc: "All'inizio esiste Eru Ilúvatar, il Creatore, origine di tutto ciò che sarà Arda.",
ainurSong: "Il Canto degli Ainur",
ainurSongDesc: "Gli Ainur intonano la Grande Musica, dalla quale nasce la visione del mondo futuro.",
ardaVision: "La visione di Arda",
ardaVisionDesc: "La Musica prende forma nella visione di Arda, il mondo destinato a diventare realtà.",
valarAgainstMelkor: "I Valar contro Melkor",
valarAgainstMelkorDesc: "Melkor si oppone all'ordine degli altri Ainur e diventa la prima grande forza di discordia.",
firstWar: "La prima guerra",
firstWarDesc: "I Valar combattono Melkor per il dominio di Arda, sconvolgendo il mondo ancora giovane.",
valarDescent: "La discesa dei Valar",
valarDescentDesc: "I Valar entrano in Arda per plasmarla e prepararla alla venuta dei Figli di Ilúvatar.",
twoLamps: "Le Due Lampade",
twoLampsDesc: "Illuin e Ormal illuminano Arda, portando luce nelle terre ancora prive del Sole e della Luna.",
awakeningOfElves: "Il risveglio degli Elfi",
awakeningOfElvesDesc: "A Cuiviénen si risvegliano i primi Elfi, i Primogeniti di Ilúvatar.",
eldar: "Gli Eldar",
eldarDesc: "Molti Elfi accettano l'invito dei Valar e intraprendono la Grande Marcia verso Occidente.",
silmarilsCreation: "La creazione dei Silmaril",
silmarilsCreationDesc: "Fëanor forgia i tre Silmaril, racchiudendo in essi la luce dei Due Alberi di Valinor.",
deathOfFinwe: "La morte di Finwë",
deathOfFinweDesc: "Melkor torna in azione, uccide Finwë e sottrae i Silmaril dalla casa di Fëanor.",
melkorUngoliant: "Melkor e Ungoliant",
melkorUngoliantDesc: "Melkor si allea con Ungoliant, che insieme causano la morte dei Due Alberi di Valinor.",
silmarilsTheft: "Il furto dei Silmaril",
silmarilsTheftDesc: "Dopo la morte di Finwë, Melkor fugge da Valinor portando con sé i Silmaril.",
feanorOath: "Il Giuramento di Fëanor",
feanorOathDesc: "Fëanor e i suoi figli giurano di perseguire chiunque possieda o sottragga i Silmaril.",
alqualonde: "La strage di Alqualondë",
alqualondeDesc: "I Noldor attaccano i Teleri per impossessarsi delle loro navi. È il primo dei grandi massacri fratricidi.",
judgmentOfMandos: "Il Giudizio di Mandos",
judgmentOfMandosDesc: "Mandos pronuncia il giudizio sui Noldor e sulle conseguenze della loro ribellione.",
sunAndMoon: "Il Sole e la Luna",
sunAndMoonDesc: "Dopo la distruzione degli Alberi, il Sole e la Luna sorgono finalmente nei cieli di Arda.", 
helcaraxe: "Attraverso il Helcaraxë",
helcaraxeDesc: "Fingolfin e i suoi seguaci affrontano il terribile passaggio del Ghiaccio Macinatore per raggiungere la Terra di Mezzo.",
beleriand: "Il Beleriand",
beleriandDesc: "I Noldor giungono nel Beleriand e sorgono nuovi regni elfici destinati a diventare il cuore della Prima Era.",
morgothRegroups: "Morgoth si riorganizza",
morgothRegroupsDesc: "Nel nord, Morgoth ricostruisce Angband e raduna le forze che presto minacceranno tutti i regni del Beleriand.",
dagorNuinGiliath: "La Dagor-nuin-Giliath",
dagorNuinGiliathDesc: "I Noldor affrontano gli eserciti di Morgoth nella prima grande battaglia dopo il loro ritorno nella Terra di Mezzo.",
fallOfFingolfin: "La caduta di Fingolfin",
fallOfFingolfinDesc: "Fingolfin sfida Morgoth alle porte di Angband e combatte da solo contro il Signore Oscuro.",
berenMeetsLuthien: "Beren incontra Lúthien",
berenMeetsLuthienDesc: "Nella foresta di Doriath, Beren incontra Lúthien e ha inizio una delle più grandi storie d'amore di Arda.",
silmaril: "Il Silmaril",
silmarilDesc: "Beren strappa un Silmaril dalla corona di Morgoth e porta a compimento la missione.",
berenCarcharoth: "Beren e Carcharoth",
berenCarcharothDesc: "Carcharoth inghiotte il Silmaril e fugge attraverso Doriath, inseguito da Beren.",
silmarilRecovered: "Il Silmaril recuperato",
silmarilRecoveredDesc: "La caccia a Carcharoth conduce alla riconquista del Silmaril e alla conclusione della grande impresa di Beren e Lúthien.",
turinGlaurung: "Túrin e Glaurung",
turinGlaurungDesc: "La vita di Túrin diventa una delle più oscure tragedie della Prima Era, legata indissolubilmente al drago Glaurung.",
fallOfNargothrond: "La caduta di Nargothrond",
fallOfNargothrondDesc: "Glaurung conduce gli eserciti di Morgoth alla distruzione del grande regno sotterraneo.",
fallOfGondolin: "La caduta di Gondolin",
fallOfGondolinDesc: "Il regno nascosto di Turgon viene scoperto e distrutto dalle forze di Morgoth.",
escapeFromGondolin: "La fuga da Gondolin",
escapeFromGondolinDesc: "Tuor, Idril e i superstiti riescono a fuggire dalla città in rovina e a raggiungere le foci del Sirion.",
earendilElwing: "Eärendil ed Elwing",
earendilElwingDesc: "Alle foci del Sirion si intrecciano le vicende delle ultime grandi stirpi degli Elfi e degli Uomini.",
elwingReachesEarendil: "Elwing raggiunge Eärendil",
elwingReachesEarendilDesc: "Elwing raggiunge Eärendil portando il Silmaril, dopo la distruzione dei rifugi del Sirion.", 
earendilJourney: "Il viaggio di Eärendil",
earendilJourneyDesc: "Eärendil naviga verso Occidente alla ricerca della terra dei Valar, portando con sé il Silmaril.",
earendilReachesAman: "Eärendil raggiunge Aman",
earendilReachesAmanDesc: "Dopo il lungo viaggio attraverso i mari dell'Occidente, Eärendil raggiunge le coste di Aman.",
pleaToValar: "La supplica ai Valar",
pleaToValarDesc: "Eärendil porta ai Valar la richiesta di aiuto degli Elfi e degli Uomini contro Morgoth.",
vingilot: "Vingilot",
vingilotDesc: "Eärendil diventa il portatore del Silmaril nei cieli, simbolo di speranza per coloro che ancora combattono contro Morgoth.",
lastChildren: "Gli ultimi figli delle grandi stirpi",
lastChildrenDesc: "Le vicende della Prima Era lasciano un'eredità destinata a sopravvivere nelle Ere successive.",
finalConfrontationPreparation: "La preparazione dello scontro finale",
finalConfrontationPreparationDesc: "Morgoth raccoglie le sue ultime grandi forze per affrontare l'esercito dei Valar.",
morgothArmy: "L'esercito di Morgoth",
morgothArmyDesc: "Orchi, Balrog, draghi e altre creature oscure vengono schierati per la battaglia decisiva.",
warOfWrath: "La Guerra dell'Ira",
warOfWrathDesc: "Gli eserciti dell'Occidente giungono nella Terra di Mezzo e ha inizio la guerra che porrà fine al dominio di Morgoth.",
fallOfAncalagon: "La caduta di Ancalagon",
fallOfAncalagonDesc: "Eärendil affronta Ancalagon il Nero nei cieli e contribuisce alla definitiva sconfitta delle forze di Morgoth.",
captureOfMorgoth: "La cattura di Morgoth",
captureOfMorgothDesc: "Dopo la sconfitta, Morgoth viene catturato dalle forze dei Valar e privato del suo potere.",
morgothDefeated: "Morgoth sconfitto",
morgothDefeatedDesc: "La Guerra dell'Ira termina con la sconfitta di Morgoth e la caduta del suo dominio.",
morgothCrown: "La corona di Morgoth",
morgothCrownDesc: "La corona che aveva contenuto i Silmaril rimane come testimonianza della grande caduta del Signore Oscuro.",
gatesOfVoid: "Alle porte del Vuoto",
gatesOfVoidDesc: "Morgoth viene condotto davanti alla soglia oltre la quale sarà bandito per sempre.",
morgothInVoid: "Morgoth nel Vuoto",
morgothInVoidDesc: "Morgoth viene espulso oltre le mura del mondo e la sua presenza in Arda giunge alla fine.",
endOfBeleriand: "La fine del Beleriand",
endOfBeleriandDesc: "La Guerra dell'Ira sconvolge il continente: gran parte del Beleriand sprofonda nelle acque e la Prima Era giunge al termine.",
  
  
secondAge: "LA SECONDA ERA",

 
secondAgeType: "L'ascesa e la caduta dei regni, Númenor e la forgiatura degli Anelli.",
        secondAgeSubtitle: "L'ascesa e la caduta dei regni, Númenor e la forgiatura degli Anelli.",
        saTitle1: "Lindon e i Porti Grigi",
        saDesc1: "Lindon e i porti occidentali degli Elfi diventano il centro della presenza elfica nella Terra di Mezzo.",
        saTitle2: "Númenor",
        saDesc2: "L'isola di Númenor diventa la grande patria degli Edain, al centro della storia della Seconda Era.",
        saTitle3: "Espansione di Númenor",
        saDesc3: "I Númenóreani iniziano a esplorare e frequentare le coste della Terra di Mezzo, ampliando la loro influenza.",
        saTitle4: "Il ritorno di Sauron nella Terra di Mezzo",
        saDesc4: "Sauron torna nella Terra di Mezzo e comincia nuovamente a radunare potere e servitori.",
        saTitle5: "Eregion",
        saDesc5: "Gli Elfi fondano Eregion presso le Montagne Nebbiose, trasformandola in un grande centro di arti e forgiatura.",
        saTitle6: "Annatar e Celebrimbor",
        saDesc6: "Sauron, sotto le sembianze di Annatar, si presenta agli Elfi e conquista la fiducia di Celebrimbor.",
        saTitle7: "Gli Anelli del Potere",
        saDesc7: "Gli artigiani di Eregion forgiano gli Anelli del Potere sotto l'influenza degli insegnamenti di Annatar.",
        saTitle8: "Gli Anelli Elfici",
        saDesc8: "Celebrimbor e i fabbri elfici realizzano i Tre Anelli, destinati a preservare e proteggere ciò che è bello nella Terra di Mezzo.",
        saTitle9: "La consegna degli Anelli Elfici",
        saDesc9: "I Tre Anelli vengono affidati ai grandi signori elfici e sottratti all'influenza diretta di Sauron.",
        saTitle10: "Sauron forgia l'Unico",
        saDesc10: "Sauron forgia l'Unico Anello per dominare gli altri Anelli del Potere e i loro portatori.",
        saTitle11: "Invasione nell'Eriador",
        saDesc11: "Gli eserciti di Sauron invadono l'Eriador e avanzano contro i domini degli Elfi.",
        saTitle12: "Fine dell'Eregion",
        saDesc12: "Eregion viene devastata e Celebrimbor viene ucciso; la regione perde per sempre il suo ruolo di grande centro elfico.",
        saTitle13: "Sauron si impossessa dei Nove Anelli",
        saDesc13: "Sauron entra in possesso dei Nove Anelli destinati agli Uomini.",
        saTitle14: "Ritirata a Mordor",
        saDesc14: "Dopo la guerra, Sauron concentra nuovamente il proprio potere nelle terre di Mordor.",
        saTitle15: "La consegna dei Nove",
        saDesc15: "I Nove Anelli vengono consegnati da Sauron a uomini potenti, che nel tempo diventeranno i Nazgûl.",
        saTitle16: "Númenóreani in soccorso degli Elfi",
        saDesc16: "La grande flotta di Númenor giunge nella Terra di Mezzo e costringe Sauron a ritirarsi.",
        saTitle17: "Espansioni Númenóreane",
        saDesc17: "I Númenóreani consolidano la loro presenza sulle coste della Terra di Mezzo e fondano nuovi insediamenti.",
        saTitle18: "Sauron conquista acuni insediamenti",
        saDesc18: "L'influenza di Sauron cresce nella Terra di Mezzo minacciando i domini númenóreani.",
        saTitle19: "Umbar",
        saDesc19: "Umbar diventa una delle grandi fortezze e basi navali dei Númenóreani nella Terra di Mezzo.",
        saTitle20: "Pelargir",
        saDesc20: "Pelargir viene fondata come grande porto dei Númenóreani Fedeli sulle rive dell'Anduin.",
        saTitle21: "Ar-Pharazôn",
        saDesc21: "Ar-Pharazôn sale al trono di Númenor e diventa il più potente dei re dell'isola.",
        saTitle22: "Ar-Pharazôn viene a sapere di Sauron",
        saDesc22: "Ar-Pharazôn apprende della crescente minaccia di Sauron e decide di affrontarlo",
        saTitle23: "Ar-Pharazôn prepara la sua armata",
        saDesc23: "Il re di Númenor prepara una grande armata per sottomettere Sauron.",
        saTitle24: "Sauron e Ar-Pharazôn",
        saDesc24: "Ar-Pharazôn giunge nella Terra di Mezzo e Sauron comprende di non poterlo sconfiggere con la forza.",
        saTitle25: "Sauron si consegna ad Ar-Pharazôn",
        saDesc25: "Sauron sceglie di arrendersi volontariamente e si lascia condurre prigioniero a Númenor.",
        saTitle26: "Sauron viene portato a Númenor",
        saDesc26: "Sauron viene condotto nell'isola come prigioniero, ma prepara rapidamente la propria vendetta.",
        saTitle27: "La corruzione di Sauron",
        saDesc27: "Sauron conquista la fiducia di Ar-Pharazôn e inizia a corrompere la corte e la società di Númenor.",
        saTitle28: "Ar-Pharazôn contro i Valar",
        saDesc28: "Sauron convince Ar-Pharazôn che la morte è un inganno e lo spinge contro Aman.",
        saTitle29: "Tensioni a Númenór",
        saDesc29: "Nella società di Númenor cresce la frattura tra i Fedeli ai Valar e coloro che desiderano maggiore potere e dominio.",
        saTitle30: "la decisione di amandil",
        saDesc30: "Amandil, padre di Elendil, decide di tentare una disperata navigazione verso Aman per chiedere aiuto ai Valar.",
        saTitle31: "Elendil prepara la spedizione",
        saDesc31: "Elendil prepara le navi dei Fedeli per fuggire da Númenor prima della sua inevitabile rovina.",
        saTitle32: "Amandil parte per Aman",
        saDesc32: "Amandil salpa verso occidente nel tentativo di raggiungere Aman e implorare la misericordia dei Valar.",
        saTitle33: "Ar-Pharazôn parte per Aman",
        saDesc33: "Ar-Pharazôn salpa con la Grande Armata per Aman per ottenere l'immortalità.",
        saTitle34: "Ar-Pharazôn sulle rive di Aman",
        saDesc34: "La flotta di Ar-Pharazôn raggiunge le rive di Aman, oltrepassando il limite imposto.",
        saTitle35: "Manwë si rivolge a Eru",
        saDesc35: "Di fronte alla ribellione degli Uomini, Manwë invoca Eru Ilúvatar e affida a lui il destino di Arda.",
        saTitle36: "Eru estrapola Aman",
        saDesc36: "Eru interviene nella storia di Arda e ne muta la struttura, separando Aman dal mondo.",
        saTitle37: "Distruzione di Númenor",
        saDesc37: "Númenor viene sommersa e distrutta; Elendil e i Fedeli viaggiano verso la Terra di Mezzo.",
        saTitle38: "Sauron viene distrutto",
        saDesc38: "La distruzione di Númenor annienta il corpo di Sauron, ma non il suo spirito: l’Unico Anello rimane con lui.",
        saTitle39: "Sauron in spirito torna a Mordor",
        saDesc39: "sauron torna a mordor in spirito e si riorganizza.",
        saTitle40: "il corpo di sauron",
        saDesc40: "Sauron riesce nel tempo a ricostituire una forma fisica fittizia, non riavendo più il suo aspetto originario.",
        saTitle41: "Mappa spedizione Elendil",
        saDesc41: "La spedizione dei Fedeli si divide: Elendil raggiunge il nord, mentre Isildur e Anárion navigano verso il sud e l'Anduin.",
        saTitle42: "Gli Uomini delle Montagne",
        saDesc42: "Gli Uomini delle Montagne riconoscono il potere di Sauron e gli prestano servizio.",
        saTitle43: "Costruzione di Arnor",
        saDesc43: "Elendil fonda Arnor nel nord e stabilisce il regno dei Dúnedain settentrionali.",
        saTitle44: "Costruzione di Gondor",
        saDesc44: "Isildur e Anárion fondano Gondor nel sud, dando vita al grande regno dei Dúnedain della Terra di Mezzo.",
        saTitle45: "Giuramento a Isildur",
        saDesc45: "Il re degli Uomini delle Montagne giura fedeltà a Isildur presso la Pietra di Erech.",
        saTitle46: "Gil-galad ed Elendil contro Sauron",
        saDesc46: "Alla fine dell'assedio, Gil-galad ed Elendil affrontano direttamente Sauron alle pendici di Orodruin.",
        saTitle47: "Sauron conquista Minas Ithil",
        saDesc47: "Sauron attacca Gondor e conquista Minas Ithil, che diventa Minas Morgul molti anni dopo.",
        saTitle48: "l'anatema di Isildur",
        saDesc48: "Gli Uomini delle Montagne infrangono il giuramento; non troveranno pace fino a giuramento onorato.",
        saTitle49: "Alleanza a Imladris",
        saDesc49: "Elfi e Dúnedain si uniscono nella Last Alliance, mentre le forze alleate si concentrano a Imladris.",
        saTitle50: "Battaglia di Dagorlad",
        saDesc50: "La Last Alliance affronta le forze di Sauron nella grande Battaglia di Dagorlad e ottiene la vittoria.",
        saTitle51: "Alleanza marcia verso Barad-Dûr",
        saDesc51: "L'esercito della Last Alliance attraversa la Terra di Mezzo e marcia verso Mordor.",
        saTitle52: "Assedio a Barad-Dûr",
        saDesc52: "Dopo la vittoria a Dagorlad, le forze dell'Alleanza entrano in Mordor e assediano Barad-dûr per sette anni.",
        saTitle53: "Sauron contro Gil-galad ed Elendil",
        saDesc53: "Nel confronto finale, Sauron affronta Gil-galad ed Elendil e uccide entrambi i Re.",
        saTitle54: "Isildur sconfigge Sauron",
        saDesc54: "Isildur recide il dito di Sauron con il frammento dell'elsa di Narsil e prende l'Unico.",
        saTitle55: "Distruzione di Sauron",
        saDesc55: "Separato dall'Unico, Sauron perde il potere dell'Anello e il suo corpo viene distrutto.",
        saTitle56: "Isildur e l'Unico",
        saDesc56: "Isildur rimane in possesso dell'Unico Anello, mentre la Seconda Era giunge al termine.",
thirdAge: "LA TERZA ERA",
thirdAgeType: "L'epoca dei grandi regni e della Guerra dell'Anello.",
pageTitleThirdAge: "Prisma Realm — La Terza Era",
ardaCharacters: "PERSONAGGI",
ardaCharactersType: "Eroi, re, elfi, guerrieri, creature e figure leggendarie.",
ardaPlaces: "LUOGHI",
ardaPlacesType: "Regni, città, foreste, montagne e terre dimenticate.",
ardaCreatures: "CREATURE",
ardaCreaturesType: "Bestie, mostri ed esseri che abitano il mondo di Arda.",
eternalKingdoms: "I REGNI ETERNI",
eternalKingdomsType: "Regni di re, castelli e antichi poteri",
wildlands: "LE TERRE SELVAGGE",
wildlandsType: "Paesaggi incontaminati e luoghi dimenticati",
darkRealms: "I REGNI OSCURI",
darkRealmsType: "Terre nell'ombra, rovine e regni proibiti",
celestialRealms: "I REGNI CELESTIALI",
celestialRealmsType: "Mondi oltre i confini della realtà",
forgottenLands: "LE TERRE DIMENTICATE",
forgottenLandsType: "Civiltà perdute e misteri del passato",
latestArtworks: "ULTIME OPERE",
lostValley: "LA VALLE PERDUTA",
dragonOfAsh: "DRAGO DI CENERE",
dragonType: "Fantasy · Creatura",
citadelInClouds: "CITTÀ DELLE NUVOLE",
citadelType: "Fantasy · Ambientazione",
landscapes: "PAESAGGI",
landscapesType: "Luoghi e orizzonti",
ancientForest: "FORESTA ANTICA",
landscapeType: "Fantasy · Paesaggio",
fallenKing: "IL RE CADUTO",
fallenKingType: "Dark Fantasy · Personaggio",
shatteredRealm: "REGNO FRANTUMATO",
shatteredRealmType: "Dark Fantasy · Ambientazione",
fantasy: "FANTASY",
fantasyType: "Mondi epici e leggende",
creatures: "CREATURE",
creaturesType: "Bestie ed esseri",
worlds: "MONDI",
worldsType: "Regni e dimensioni",
characters: "PERSONAGGI",
charactersType: "Eroi e malvagi",
darkFantasy: "DARK FANTASY",
darkFantasyType: "Ombre e corruzione",
exploreCategories: "ESPLORA CATEGORIE",
whereImaginationTakesForm: "DOVE L'IMMAGINAZIONE PRENDE FORMA",
navigation: "NAVIGAZIONE",
info: "INFO",
termsOfUse: "Termini di utilizzo",
privacyPolicy: "Informativa sulla privacy",
cookiesPolicy: "Politica sui cookie",
stayUpdated: "RESTA AGGIORNATO",
newArtworks: "Nuove opere, dietro le quinte e contenuti esclusivi.",
emailPlaceholder: "Il tuo indirizzo email"
	}

};


const thirdAgeSceneTranslations = {
    ta1_title: "The Death of Isildur",
    ta1_desc: "Isildur, attacked by Orcs, loses the One Ring in the Anduin.",
    ta2_title: "Arrival of the Blue Wizards",
    ta2_desc: "The two Blue Wizards arrive in Middle-earth and journey towards the eastern regions.",
    ta3_title: "Arrival of Saruman",
    ta3_desc: "Saruman arrives in Middle-earth as one of the Istari sent to oppose Sauron's power.",
    ta4_title: "Arrival of Radagast",
    ta4_desc: "Radagast arrives in Middle-earth and establishes his bond with animals and the wild lands.",
    ta5_title: "Arrival of Gandalf",
    ta5_desc: "Gandalf arrives at the Grey Havens, where Círdan gives him Narya, one of the Three Elven Rings.",
    ta6_title: "Sméagol and Déagol",
    ta6_desc: "Sméagol and Déagol fish in the Anduin and discover the One Ring in the river.",
    ta7_title: "The Death of Déagol",
    ta7_desc: "The corruption of the One drives Sméagol to kill Déagol.",
    ta8_title: "Gollum in the Mountains",
    ta8_desc: "Corrupted by the Ring, Sméagol becomes Gollum and takes refuge in the mountains.",
    ta9_title: "Arnor",
    ta9_desc: "Elendil founds Arnor and establishes its capital at Annúminas, on the shores of Lake Nenuial.",
    ta10_title: "Gondor",
    ta10_desc: "Isildur and Anárion found Gondor, with Minas Ithil, Minas Anor and Osgiliath along the Anduin.",
    ta11_title: "The Argonath",
    ta11_desc: "The statues of Isildur and Anárion watch over the Anduin at the entrance to Gondor.",
    ta12_title: "Arnor Divided into Three Realms",
    ta12_desc: "After Eärendur’s death, Arnor divides into Arthedain, Cardolan and Rhudaur.",
    ta13_title: "The Rise of Angmar",
    ta13_desc: "The Witch-king founds Angmar and gathers Orcs, evil Men and other creatures under his rule.",
    ta14_title: "The Fall of Arnor",
    ta14_desc: "Angmar destroys Arthedain, bringing the kingdom of Arnor in the North to an end.",
    ta15_title: "The Fall of Angmar",
    ta15_desc: "The kingdom of Angmar is defeated by the army of Gondor and the Dúnedain, and the Witch-king flees to Mordor.",
    ta16_title: "The Kin-strife",
    ta16_desc: "Eldacar and Castamir contest the throne of Gondor in the bloody Kin-strife.",
    ta17_title: "Partial Destruction of Osgiliath",
    ta17_desc: "During the Kin-strife, Osgiliath is devastated and the Great Bridge is destroyed.",
    ta18_title: "The Great Plague",
    ta18_desc: "The Great Plague strikes Gondor and spreads through Middle-earth, causing thousands of deaths.",
    ta19_title: "The Capture of Minas Ithil",
    ta19_desc: "After a two-year siege, the Nazgûl conquer Minas Ithil.",
    ta20_title: "Minas Morgul",
    ta20_desc: "Minas Ithil becomes Minas Morgul, a dark fortress of the Nazgûl and stronghold of Mordor.",
    ta21_title: "The End of the Kings of Gondor",
    ta21_desc: "Eärnur, the last King of Gondor, enters Minas Morgul and never returns.",
    ta22_title: "Khazad-dûm",
    ta22_desc: "The prosperous underground realm of the Dwarves in the Misty Mountains.",
    ta23_title: "The Dwarves in the Mines",
    ta23_desc: "The Dwarves delve into the depths of Khazad-dûm, unaware of what lies in the shadows.",
    ta24_title: "Durin VI and the Balrog",
    ta24_desc: "Durin VI confronts the Balrog awakened in the depths of Khazad-dûm.",
    ta25_title: "The Dwarves Abandon Moria",
    ta25_desc: "The Dwarves flee Khazad-dûm after the death of Durin VI.",
    ta26_title: "The Dwarven Migration",
    ta26_desc: "The Dwarves migrate to Erebor, the Lonely Mountain.",
    ta27_title: "Erebor",
    ta27_desc: "The Dwarves establish the Kingdom Under the Mountain at the foot of Erebor.",
    ta28_title: "Thráin I and the Arkenstone",
    ta28_desc: "Thráin I becomes King Under the Mountain and finds the Arkenstone.",
    ta29_title: "Smaug Conquers Erebor",
    ta29_desc: "Smaug arrives at Erebor and drives the Dwarves from the Mountain.",
    ta30_title: "The Destruction of Dale",
    ta30_desc: "Smaug destroys Dale and the kingdom of Men at the foot of Erebor.",
    ta31_title: "Sauron Returns to Dol Guldur",
    ta31_desc: "Sauron settles in Dol Guldur under the guise of the Necromancer.",
    ta32_title: "The White Council",
    ta32_desc: "The White Council gathers to oppose the Necromancer of Dol Guldur.",
    ta33_title: "The Necromancer Revealed",
    ta33_desc: "The Council confronts the Necromancer and discovers his identity.",
    ta34_title: "Sauron Is Driven Out",
    ta34_desc: "The White Council drives Sauron from Dol Guldur.",
    ta35_title: "The Rebuilding of Barad-dûr",
    ta35_desc: "Sauron rebuilds Barad-dûr and gathers his forces in Mordor.",
    ta36_title: "Thorin's Company",
    ta36_desc: "Gandalf and Thorin organize the expedition to Erebor.",
    ta37_title: "Towards Erebor",
    ta37_desc: "Thorin and his company set out for Erebor.",
    ta38_title: "Bilbo Gets Lost",
    ta38_desc: "Bilbo gets lost in the mountain's passages and meets Gollum.",
    ta39_title: "Bilbo Finds the One Ring",
    ta39_desc: "Gollum loses the One Ring and Bilbo finds it.",
    ta40_title: "The Company Reunites",
    ta40_desc: "Bilbo finds his way back to Thorin's company.",
    ta41_title: "The Secret Door of Erebor",
    ta41_desc: "Bilbo discovers the secret door of Erebor.",
    ta42_title: "Bilbo and Smaug",
    ta42_desc: "Bilbo enters Smaug's lair and confronts him.",
    ta43_title: "Bilbo Notices Smaug's Weakness",
    ta43_desc: "Bilbo discovers Smaug's weak spot.",
    ta44_title: "The Secret of Smaug",
    ta44_desc: "Bilbo reveals Smaug's weak spot to the Dwarves; a thrush listens.",
    ta45_title: "Smaug Heads for Lake-town",
    ta45_desc: "Furious, Smaug flies towards Lake-town to attack the city.",
    ta46_title: "Bard and the Thrush",
    ta46_desc: "The thrush reveals to Bard the unprotected spot on Smaug's chest.",
    ta47_title: "The Death of Smaug",
    ta47_desc: "Bard fires the Black Arrow and kills Smaug.",
    ta48_title: "The Reclaiming of Erebor",
    ta48_desc: "The Dwarves reclaim Erebor after Smaug's death.",
    ta49_title: "The Battle of the Five Armies",
    ta49_desc: "Dwarves, Men, Elves and Orcs clash in the battle for Erebor.",
    ta50_title: "The United Forces",
    ta50_desc: "Elves, Men and Dwarves join forces against Goblins and Wargs.",
    ta51_title: "The Death of Thorin",
    ta51_desc: "Thorin dies after defeating Azog in the Battle of the Five Armies.",
    ta52_title: "Thorin's Funeral",
    ta52_desc: "Thorin is buried in the Lonely Mountain, with the Arkenstone upon his chest.",
    ta53_title: "Dáin II",
    ta53_desc: "After Thorin's death, Dáin II becomes King Under the Mountain.",
    ta54_title: "The Rebirth of Dale",
    ta54_desc: "Dale is rebuilt and prospers again under Bard's rule.",
    ta55_title: "Bilbo and Gandalf",
    ta55_desc: "On the day of his 111th birthday, Bilbo prepares to leave.",
    ta56_title: "Bilbo Leaves the Shire",
    ta56_desc: "Bilbo departs and leaves his legacy to Frodo.",
    ta57_title: "Frodo Inherits the One",
    ta57_desc: "Frodo receives the One Ring from Bilbo.",
    ta58_title: "Gandalf Tests the Ring",
    ta58_desc: "Gandalf tests the Ring and realizes that it is the One.",
    ta59_title: "Gandalf Advises Frodo to Leave",
    ta59_desc: "Gandalf advises Frodo to leave the Shire and head for Bree.",
    ta60_title: "The Awakening of the Nazgûl",
    ta60_desc: "The One calls the Nazgûl, who awaken to find it.",
    ta61_title: "The Hobbits Set Out",
    ta61_desc: "Frodo, Sam, Merry and Pippin leave the Shire and head for Bree.",
    ta62_title: "The Nazgûl Leave Minas Morgul",
    ta62_desc: "The Nazgûl leave Minas Morgul and set out in search of the One.",
    ta63_title: "The Hobbits Meet Tom Bombadil",
    ta63_desc: "Frodo, Sam, Merry and Pippin meet Tom Bombadil in the Old Forest.",
    ta64_title: "The Hobbits and Tom Bombadil",
    ta64_desc: "Tom Bombadil welcomes the Hobbits into his home and hosts them for the night.",
    ta65_title: "The Hobbits Resume Their Journey",
    ta65_desc: "After leaving Tom Bombadil, the Hobbits resume their journey towards Bree.",
    ta66_title: "The Hobbits in the Mist",
    ta66_desc: "The Hobbits travel through the mist as they continue towards Bree.",
    ta67_title: "In the Barrow-downs",
    ta67_desc: "The Hobbits enter the desolate Barrow-downs.",
    ta68_title: "The Hobbits Attacked by Wights",
    ta68_desc: "The Hobbits are attacked by the wights of the Barrow-downs.",
    ta69_title: "The Barrow-wight",
    ta69_desc: "The Barrow-wight captures the Hobbits and drags them into the barrow.",
    ta70_title: "Tom Comes to the Rescue",
    ta70_desc: "Tom Bombadil comes to the Hobbits' aid and confronts the wights.",
    ta71_title: "Tom Saves the Hobbits",
    ta71_desc: "Tom Bombadil frees the Hobbits and brings them to safety.",
    ta72_title: "The Hobbits Arrive in Bree",
    ta72_desc: "The Hobbits reach Bree and look for a place to stay.",
    ta73_title: "The Prancing Pony",
    ta73_desc: "The Hobbits arrive at the Prancing Pony, the inn of Bree.",
    ta74_title: "Frodo Meets Strider",
    ta74_desc: "Frodo meets Strider at the Prancing Pony.",
    ta75_title: "The Nazgûl in Bree",
    ta75_desc: "The Nazgûl arrive in Bree in pursuit of the Hobbits.",
    ta76_title: "The Escape from Bree",
    ta76_desc: "The Hobbits flee Bree together with Strider.",
    ta77_title: "The Fugitives at Weathertop",
    ta77_desc: "Frodo and his companions reach Weathertop with Strider.",
    ta78_title: "The Fugitives Face the Nazgûl",
    ta78_desc: "The Nazgûl attack the Hobbits and Strider at Weathertop.",
    ta79_title: "Frodo Struck by the Witch-king",
    ta79_desc: "The Witch-king strikes Frodo with a Morgul blade.",
    ta80_title: "The Flight to Rivendell",
    ta80_desc: "The Hobbits flee towards Rivendell with Frodo wounded.",
    ta81_title: "Glorfindel Comes to the Rescue",
    ta81_desc: "Glorfindel reaches the Hobbits and aids Frodo.",
    ta82_title: "Glorfindel Leads Frodo to the Ford",
    ta82_desc: "Glorfindel sends Frodo towards the Ford of Bruinen.",
    ta83_title: "The Nazgûl Swept Away by the Bruinen",
    ta83_desc: "The Nazgûl are swept away by the waters of the Bruinen.",
    ta84_title: "Frodo in Rivendell",
    ta84_desc: "Frodo awakens in Rivendell after being rescued.",
    ta85_title: "Gandalf Tells of His Captivity",
    ta85_desc: "Gandalf tells of his captivity atop the tower of Isengard.",
    ta86_title: "Gandalf Informs Saruman of the Ring",
    ta86_desc: "Gandalf discovers Saruman's betrayal and understands the danger of the One.",
    ta87_title: "Saruman Imprisons Gandalf on the Tower",
    ta87_desc: "Saruman imprisons Gandalf atop the tower of Orthanc.",
    ta88_title: "Gandalf's Escape",
    ta88_desc: "Gandalf escapes from the tower of Orthanc and reaches safety.",
    ta89_title: "The Council of Elrond",
    ta89_desc: "The Council of Elrond decides the fate of the One Ring.",
    ta90_title: "The Fellowship of the Ring",
    ta90_desc: "The Fellowship of the Ring is formed to accompany Frodo.",
    ta91_title: "The Fellowship Sets Out",
    ta91_desc: "The Fellowship leaves Rivendell and begins the journey to Mordor.",
    ta92_title: "The Fellowship at the Gates of Moria",
    ta92_desc: "The Fellowship reaches the gates of Moria and seeks a way in.",
    ta93_title: "Inside Moria",
    ta93_desc: "The Fellowship crosses the dark mines of Moria.",
    ta94_title: "Gandalf Faces the Balrog",
    ta94_desc: "Gandalf confronts the Balrog on the Bridge of Khazad-dûm.",
    ta95_title: "Gandalf Falls with the Balrog",
    ta95_desc: "Gandalf falls into the abyss together with the Balrog.",
    ta96_title: "The Defeat of the Balrog",
    ta96_desc: "Gandalf defeats the Balrog after their struggle atop Zirakzigil.",
    ta97_title: "The Fellowship Towards Lothlórien",
    ta97_desc: "The Fellowship leaves Moria and heads towards Lothlórien.",
    ta98_title: "Galadriel and Celeborn",
    ta98_desc: "Galadriel and Celeborn welcome the Fellowship to Lothlórien.",
    ta99_title: "Galadriel's Gifts",
    ta99_desc: "Galadriel gives the Fellowship gifts for their journey.",
    ta100_title: "The Fellowship Leaves Lothlórien",
    ta100_desc: "The Fellowship leaves Lothlórien and resumes the journey.",
    ta101_title: "Towards the Lands of Gondor",
    ta101_desc: "The Fellowship reaches the lands of Gondor along the Anduin.",
    ta102_title: "The Fellowship on the Anduin",
    ta102_desc: "The Fellowship comes ashore on the banks of the Anduin.",
    ta103_title: "Boromir's Temptation",
    ta103_desc: "Boromir gives in to the temptation of the One and tries to take it.",
    ta104_title: "Frodo's Vision",
    ta104_desc: "Frodo puts on the Ring to escape Boromir and has a vision.",
    ta105_title: "Frodo Leaves the Fellowship",
    ta105_desc: "Frodo decides to continue alone towards Mordor.",
    ta106_title: "Sam Reaches Frodo",
    ta106_desc: "Sam tries to reach Frodo from the other bank of the Anduin.",
    ta107_title: "Frodo Helps Sam",
    ta107_desc: "Frodo helps Sam reach him and together they continue towards Mordor.",
    ta108_title: "Boromir Defends the Hobbits",
    ta108_desc: "Boromir defends Merry and Pippin from the attack of the Orcs.",
    ta109_title: "The Death of Boromir",
    ta109_desc: "Boromir dies defending Merry and Pippin from the Orcs.",
    ta110_title: "The Fellowship Finds Boromir",
    ta110_desc: "Aragorn, Legolas and Gimli reach Boromir as he lies dying.",
    ta111_title: "Farewell to Boromir",
    ta111_desc: "Aragorn, Legolas and Gimli bid their final farewell to Boromir.",
    ta112_title: "The Pursuit of the Orcs",
    ta112_desc: "Aragorn, Legolas and Gimli pursue the Orcs who have captured Merry and Pippin.",
    ta113_title: "The Orcs Near Fangorn",
    ta113_desc: "The Orcs and Uruk-hai make camp near Fangorn.",
    ta114_title: "The Rohirrim Attack the Orcs",
    ta114_desc: "The Rohirrim attack the Orcs during the night.",
    ta115_title: "Meeting Treebeard",
    ta115_desc: "Merry and Pippin meet Treebeard in the forest of Fangorn.",
    ta116_title: "Meeting the Rohirrim",
    ta116_desc: "The Rohirrim tell them that the Orcs were destroyed during the night.",
    ta117_title: "The Search for the Hobbits",
    ta117_desc: "Aragorn, Legolas and Gimli continue searching for Merry and Pippin.",
    ta118_title: "The Encounter in the Forest",
    ta118_desc: "Aragorn, Legolas and Gimli encounter a mysterious figure in the forest.",
    ta119_title: "Gandalf the White",
    ta119_desc: "Gandalf returns as Gandalf the White.",
    ta120_title: "Rohan",
    ta120_desc: "Gandalf and his companions reach the lands of Rohan.",
    ta121_title: "Frodo and Sam Meet Gollum",
    ta121_desc: "Frodo and Sam encounter Gollum and capture him.",
    ta122_title: "The Dead Marshes",
    ta122_desc: "Frodo and Sam cross the Dead Marshes guided by Gollum.",
    ta123_title: "Captured in Ithilien",
    ta123_desc: "Frodo and Sam are captured by the Men of Gondor in Ithilien.",
    ta124_title: "Faramir Questions the Hobbits",
    ta124_desc: "Faramir questions Frodo and Sam about their mission.",
    ta125_title: "Gollum Captured",
    ta125_desc: "Gollum is captured and brought before Faramir.",
    ta126_title: "Faramir Wants to Kill Gollum",
    ta126_desc: "Faramir decides to kill Gollum to prevent him from revealing their passage.",
    ta127_title: "Faramir Frees the Group",
    ta127_desc: "Faramir frees Frodo, Sam and Gollum and allows them to continue.",
    ta128_title: "Towards Morgul Vale",
    ta128_desc: "Frodo and Sam follow Gollum towards Morgul Vale.",
    ta129_title: "Frodo Drawn to Minas Morgul",
    ta129_desc: "Frodo is fascinated by the light of Minas Morgul.",
    ta130_title: "Cirith Ungol",
    ta130_desc: "Frodo and Sam reach Cirith Ungol following Gollum.",
    ta131_title: "The Entmoot",
    ta131_desc: "The Ents gather to decide the fate of Isengard.",
    ta132_title: "Saruman Prepares His Army",
    ta132_desc: "Saruman prepares his army against Rohan.",
    ta133_title: "Gandalf and Théoden",
    ta133_desc: "Gandalf meets Théoden at Edoras.",
    ta134_title: "Gandalf Frees Théoden",
    ta134_desc: "Gandalf frees Théoden from Saruman's influence.",
    ta135_title: "Théoden Prepares the Exodus",
    ta135_desc: "Théoden prepares the people of Rohan to leave Edoras.",
    ta136_title: "Gríma Driven from Edoras",
    ta136_desc: "Gríma is driven from Edoras.",
    ta137_title: "Théoden Entrusts the Kingdom to Éowyn",
    ta137_desc: "Théoden entrusts the rule of Rohan to Éowyn.",
    ta138_title: "Rohan's Army Towards Helm's Deep",
    ta138_desc: "Rohan's army marches towards Helm's Deep.",
    ta139_title: "Arrival at Helm's Deep",
    ta139_desc: "The army of Rohan reaches Helm's Deep.",
    ta140_title: "Rohan Prepares for Battle",
    ta140_desc: "The Rohirrim prepare to defend Helm's Deep.",
    ta141_title: "The Battle of Helm's Deep",
    ta141_desc: "The forces of Rohan face Saruman's army.",
    ta142_title: "Gandalf Arrives",
    ta142_desc: "Gandalf arrives with reinforcements and turns the tide of the battle.",
    ta143_title: "The Ents March on Isengard",
    ta143_desc: "The Ents march on Isengard with Merry and Pippin.",
    ta144_title: "The Ents Attack Isengard",
    ta144_desc: "The Ents assault Isengard and destroy its defenses.",
    ta145_title: "Isengard Isolated",
    ta145_desc: "Isengard is isolated by the Ents.",
    ta146_title: "Gandalf and the Others Arrive at Isengard",
    ta146_desc: "Gandalf and the others reach Isengard.",
    ta147_title: "Gandalf and Saruman Face Each Other",
    ta147_desc: "Gandalf confronts Saruman in the tower of Orthanc.",
    ta148_title: "Saruman and Gríma Exiled from Isengard",
    ta148_desc: "Saruman and Gríma are exiled from Isengard.",
    ta149_title: "Pippin and the Vision of Minas Tirith",
    ta149_desc: "Pippin looks into the Palantír and sees Minas Tirith.",
    ta150_title: "Gandalf and Pippin Ride to Minas Tirith",
    ta150_desc: "Gandalf and Pippin set out for Minas Tirith.",
    ta151_title: "The Three Friends with Théoden Towards Rohan",
    ta151_desc: "Aragorn, Legolas and Gimli follow Théoden towards Rohan.",
    ta152_title: "The Grey Company",
    ta152_desc: "The Grey Company reaches Aragorn and joins his mission.",
    ta153_title: "The Three at Dunharrow",
    ta153_desc: "Aragorn, Legolas and Gimli reach Dunharrow.",
    ta154_title: "The Oath of the Dead",
    ta154_desc: "Aragorn calls upon the Dead and claims their aid.",
    ta155_title: "The Army of the Dead Towards Pelargir",
    ta155_desc: "The Army of the Dead follows Aragorn towards Pelargir.",
    ta156_title: "The Army of the Dead Against the Corsairs of Umbar",
    ta156_desc: "The Army of the Dead defeats the Corsairs of Umbar.",
    ta157_title: "Aragorn Breaks the Curse",
    ta157_desc: "Aragorn frees the spirits of the Dead from their curse.",
    ta158_title: "Théoden Prepares to Reach Dunharrow",
    ta158_desc: "Théoden prepares the army to reach Dunharrow.",
    ta159_title: "Théoden Entrusts Merry to Éowyn",
    ta159_desc: "Théoden entrusts Merry to Éowyn before the departure.",
    ta160_title: "The Rohirrim Ride Towards Gondor",
    ta160_desc: "The Rohirrim ride towards Gondor for the war.",
    ta161_title: "Gandalf and Denethor",
    ta161_desc: "Gandalf meets Denethor in the Citadel of Minas Tirith.",
    ta162_title: "Pippin, Guard of the Citadel",
    ta162_desc: "Pippin serves as a guard of the Citadel.",
    ta163_title: "Sauron's Army on the Pelennor",
    ta163_desc: "Sauron's army prepares for battle on the Pelennor.",
    ta164_title: "Faramir Returns Gravely Wounded",
    ta164_desc: "Faramir returns to Minas Tirith gravely wounded.",
    ta165_title: "Denethor Tries to Burn Faramir",
    ta165_desc: "Denethor attempts to burn Faramir on a pyre.",
    ta166_title: "Pippin Runs to Gandalf to Warn Him",
    ta166_desc: "Pippin runs to Gandalf to warn him of Denethor's act.",
    ta167_title: "The Siege of Minas Tirith",
    ta167_desc: "Sauron's army lays siege to Minas Tirith.",
    ta168_title: "Gandalf Stops Denethor",
    ta168_desc: "Gandalf prevents Denethor from killing Faramir.",
    ta169_title: "The Rohirrim Arrive",
    ta169_desc: "The Rohirrim arrive to aid Gondor.",
    ta170_title: "Éowyn Cuts Off the Winged Beast's Head",
    ta170_desc: "Éowyn kills the Witch-king's winged beast.",
    ta171_title: "Éowyn Prepares to Face the Witch-king",
    ta171_desc: "Éowyn prepares to face the Witch-king.",
    ta172_title: "The Defeat of the Witch-king",
    ta172_desc: "Merry's dagger breaks the Witch-king's protection, while Éowyn strikes the final blow.",
    ta173_title: "The Witch-king Defeated Forever",
    ta173_desc: "The Witch-king is defeated for good.",
    ta174_title: "Éowyn, Merry and Faramir in the Houses of Healing",
    ta174_desc: "Éowyn, Merry and Faramir are treated in the Houses of Healing.",
    ta175_title: "Aragorn and the Company Arrive",
    ta175_desc: "Aragorn and his company arrive in Minas Tirith.",
    ta176_title: "Aragorn on the Pelennor",
    ta176_desc: "Aragorn arrives on the battlefield of the Pelennor.",
    ta177_title: "Aragorn, Legolas and Gimli Meet Gandalf",
    ta177_desc: "Aragorn, Legolas and Gimli meet Gandalf.",
    ta178_title: "Aragorn Heals Éowyn, Merry and Faramir",
    ta178_desc: "Aragorn heals Éowyn, Merry and Faramir.",
    ta179_title: "Frodo and Sam Enter the Lair",
    ta179_desc: "Frodo and Sam enter Shelob's lair.",
    ta180_title: "Frodo and Sam Inside the Lair",
    ta180_desc: "Frodo and Sam advance through the darkness of the lair.",
    ta181_title: "Shelob",
    ta181_desc: "Shelob attacks Frodo and Sam in her lair.",
    ta182_title: "The Light of Eärendil",
    ta182_desc: "Frodo uses the Light of Eärendil to face Shelob.",
    ta183_title: "Frodo and Sam Towards the Tunnel Exit",
    ta183_desc: "Frodo and Sam search for the way out of the lair.",
    ta184_title: "Sam Wounds Shelob",
    ta184_desc: "Sam wounds Shelob with his sword.",
    ta185_title: "Sam Takes the One",
    ta185_desc: "Sam takes the One from Frodo, believing him dead.",
    ta186_title: "The Orcs Take Frodo",
    ta186_desc: "The Orcs find Frodo and carry him away.",
    ta187_title: "Frodo Is Taken to the Tower of Cirith Ungol",
    ta187_desc: "Frodo is taken to the tower of Cirith Ungol.",
    ta188_title: "The Orcs Search Frodo",
    ta188_desc: "The Orcs search Frodo for the One.",
    ta189_title: "The Orcs Fight over Frodo's Mithril Coat",
    ta189_desc: "The Orcs fight over Frodo's mithril coat.",
    ta190_title: "Sam Tries to Enter the Tower",
    ta190_desc: "Sam tries to enter the tower of Cirith Ungol.",
    ta191_title: "Sam Regains Consciousness",
    ta191_desc: "Sam regains consciousness after the struggle at the tower.",
    ta192_title: "Sam Uses the Light of Eärendil",
    ta192_desc: "Sam uses the Light of Eärendil, given by Galadriel, to enter the tower.",
    ta193_title: "Sam Inside the Tower",
    ta193_desc: "Sam enters the tower of Cirith Ungol.",
    ta194_title: "Sam Finds Frodo",
    ta194_desc: "Sam finds Frodo imprisoned in the tower.",
    ta195_title: "Sam and Frodo in Orc Disguises",
    ta195_desc: "Sam and Frodo disguise themselves with Orc gear.",
    ta196_title: "Frodo and Sam Leave the Tower",
    ta196_desc: "Frodo and Sam leave the tower of Cirith Ungol.",
    ta197_title: "Frodo and Sam Towards Mordor",
    ta197_desc: "Frodo and Sam make their way towards Mordor.",
    ta198_title: "Frodo and Sam Intercepted by Orcs",
    ta198_desc: "Frodo and Sam are stopped by a patrol of Orcs.",
    ta199_title: "Frodo and Sam Among the Orcs",
    ta199_desc: "Frodo and Sam disguise themselves among the Orcs to cross Mordor.",
    ta200_title: "The Final Council",
    ta200_desc: "The allies gather to decide the fate of the war.",
    ta201_title: "The Council and the War Plans",
    ta201_desc: "The commanders discuss plans to face the forces of Mordor.",
    ta202_title: "The Army Towards the Black Gate",
    ta202_desc: "The army of the allies marches towards the Black Gate.",
    ta203_title: "The Black Gate",
    ta203_desc: "The army of the allies reaches the Black Gate of Mordor.",
    ta204_title: "The Black Gate",
    ta204_desc: "The forces of the allies take position before the Black Gate.",
    ta205_title: "Frodo and Sam Slip Away from the Orcs",
    ta205_desc: "Frodo and Sam slip away from the Orcs to continue towards Mount Doom.",
    ta206_title: "Frodo and Sam Towards Mount Doom",
    ta206_desc: "Frodo and Sam advance towards Mount Doom through Mordor.",
    ta207_title: "Frodo Exhausted",
    ta207_desc: "Frodo, now exhausted, struggles to continue the journey.",
    ta208_title: "Sam Carries Frodo",
    ta208_desc: "Sam carries Frodo on his back towards Mount Doom.",
    ta209_title: "Frodo Tries to Cast Away the One",
    ta209_desc: "Frodo reaches Mount Doom and tries to destroy the One.",
    ta210_title: "Gollum Attacks Frodo",
    ta210_desc: "Gollum attacks Frodo to seize the One.",
    ta211_title: "Gollum Falls with the Ring",
    ta211_desc: "Gollum falls into the fire of Mount Doom with the One.",
    ta212_title: "The Ring",
    ta212_desc: "The One falls into the fire of Mount Doom.",
    ta213_title: "The Ring",
    ta213_desc: "The One is swallowed by the flames of Mount Doom.",
    ta214_title: "The Destruction of the Ring",
    ta214_desc: "The One is destroyed in the fire of Mount Doom.",
    ta215_title: "The Destruction of Barad-dûr",
    ta215_desc: "With the destruction of the One, Barad-dûr collapses.",
    ta216_title: "The Battle at the Black Gate",
    ta216_desc: "The forces of Mordor are defeated at the Black Gate.",
    ta217_title: "Sauron's Army in Rout",
    ta217_desc: "Sauron's army flees after the destruction of the One.",
    ta218_title: "The Flight of Sauron's Army",
    ta218_desc: "The forces of Mordor scatter in flight.",
    ta219_title: "Frodo and Sam Exhausted on the Slopes of Mount Doom",
    ta219_desc: "Frodo and Sam, exhausted, await rescue on Mount Doom.",
    ta220_title: "Eagles Come to the Hobbits' Rescue",
    ta220_desc: "The Eagles come to the aid of Frodo and Sam.",
    ta221_title: "Aragorn Heals the Two Hobbits",
    ta221_desc: "Aragorn heals Frodo and Sam after their rescue.",
    ta222_title: "Frodo and Sam Receive Honours",
    ta222_desc: "Frodo and Sam receive great honours for their deed.",
    ta223_title: "Return to Minas Tirith",
    ta223_desc: "The Company returns to Minas Tirith after the war.",
    ta224_title: "Aragorn Becomes King",
    ta224_desc: "Aragorn is crowned King of Gondor.",
    ta225_title: "Gandalf Leads Aragorn to Mount Mindolluin",
    ta225_desc: "Gandalf leads Aragorn to Mount Mindolluin.",
    ta226_title: "The Young White Tree",
    ta226_desc: "Aragorn finds the young sapling of the White Tree.",
    ta227_title: "Aragorn Plants the New White Tree",
    ta227_desc: "Aragorn plants the new White Tree in Minas Tirith.",
    ta228_title: "Arwen and Elrond Arrive in Minas Tirith",
    ta228_desc: "Arwen and Elrond arrive in Minas Tirith.",
    ta229_title: "The Marriage of Aragorn and Arwen",
    ta229_desc: "Aragorn and Arwen celebrate their marriage.",
    ta230_title: "The Hobbits' Ceremony of Honour",
    ta230_desc: "The Hobbits receive a ceremony of honour for their deed.",
    ta231_title: "The Company Reaches Edoras",
    ta231_desc: "The group reaches Edoras during the journey home.",
    ta232_title: "Faramir and Éowyn",
    ta232_desc: "Faramir and Éowyn make their betrothal official in Edoras.",
    ta233_title: "Honour to Théoden",
    ta233_desc: "The friends pay tribute to Théoden during the funeral ceremony.",
    ta234_title: "Arrival at Isengard",
    ta234_desc: "The group reaches Isengard during the journey home.",
    ta235_title: "Meeting Treebeard",
    ta235_desc: "The Hobbits meet Treebeard at Isengard.",
    ta236_title: "Arrival at Rivendell",
    ta236_desc: "Frodo and the others reach Rivendell.",
    ta237_title: "Meeting Bilbo in Rivendell",
    ta237_desc: "Frodo meets Bilbo in Rivendell.",
    ta238_title: "Departure for Bree",
    ta238_desc: "Frodo, Sam, Merry and Pippin leave Rivendell and set out for Bree.",
    ta239_title: "Parting from Gandalf",
    ta239_desc: "Gandalf parts from the Hobbits during the journey.",
    ta240_title: "Arrival in Hobbiton",
    ta240_desc: "The Hobbits return to Hobbiton.",
    ta241_title: "The Scouring of the Shire",
    ta241_desc: "The Hobbits discover the occupation of the Shire.",
    ta242_title: "The Hobbits' Revolt",
    ta242_desc: "The Hobbits rebel against the occupiers of Hobbiton.",
    ta243_title: "Saruman's Mask Falls",
    ta243_desc: "Frodo discovers Saruman's role in the occupation of the Shire.",
    ta244_title: "Frodo Drives Out Saruman and Gríma",
    ta244_desc: "Frodo confronts Saruman and Gríma in Hobbiton.",
    ta245_title: "Gríma Flees after Killing Saruman",
    ta245_desc: "Gríma kills Saruman and flees from Hobbiton.",
    ta246_title: "Gríma Dies beneath the Hobbits' Arrows",
    ta246_desc: "Gríma is killed by the Hobbits' arrows.",
    ta247_title: "Rebuilding Hobbiton",
    ta247_desc: "The Hobbits rebuild Hobbiton after the liberation.",
    ta248_title: "Frodo Still Suffers from Old Wounds",
    ta248_desc: "The wounds suffered during the journey continue to torment Frodo.",
    ta249_title: "Sam Marries Rosie Cotton",
    ta249_desc: "Sam marries Rosie Cotton in Hobbiton.",
    ta250_title: "Two Years Later",
    ta250_desc: "Two years pass after the Hobbits return to the Shire.",
    ta251_title: "Frodo Still Bears the Weight and Wounds of the War",
    ta251_desc: "Frodo still suffers from his war wounds.",
    ta252_title: "Frodo Decides to Leave for Rivendell",
    ta252_desc: "Frodo decides to leave the Shire and depart for Rivendell.",
    ta253_title: "Frodo Visits Sam Before Leaving",
    ta253_desc: "Frodo says farewell to Sam before leaving Hobbiton.",
    ta254_title: "Sam Accompanies Frodo on the Journey",
    ta254_desc: "Sam accompanies Frodo on the journey to the Grey Havens.",
    ta255_title: "Frodo and Sam Meet the Elves",
    ta255_desc: "Frodo and Sam meet Elves during the journey.",
    ta256_title: "Arrival at the Grey Havens",
    ta256_desc: "Frodo and Sam reach the Grey Havens.",
    ta257_title: "Farewell to Friends",
    ta257_desc: "Frodo says farewell to his friends before departing.",
    ta258_title: "Return Home",
    ta258_desc: "Sam returns home to his family.",
    ta259_title: "The End",
    ta259_desc: "The story of the Third Age comes to its conclusion.",
};

function setLanguage(lang) {

    const languageButton = document.getElementById("language-toggle");

    if (languageButton) {
        languageButton.textContent = lang.toUpperCase();
    }

    document.querySelectorAll("[data-i18n]").forEach(element => {

        const key = element.getAttribute("data-i18n");

        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }

    });

    document.querySelectorAll("[data-scene-i18n]").forEach(element => {

        const key = element.getAttribute("data-scene-i18n");

        if (lang === "en" && thirdAgeSceneTranslations[key]) {
            element.textContent = thirdAgeSceneTranslations[key];
        } else if (lang === "it" && element.dataset.itText !== undefined) {
            element.textContent = element.dataset.itText;
        }

    });

    if (translations[lang] && translations[lang].pageTitleThirdAge) {
        document.title = translations[lang].pageTitleThirdAge;
    }

    document.documentElement.classList.add("language-ready");

    localStorage.setItem("prismaLanguage", lang);
}


function toggleLanguage() {
    const currentLanguage = localStorage.getItem("prismaLanguage") || "en";
    setLanguage(currentLanguage === "en" ? "it" : "en");
}


document.addEventListener("DOMContentLoaded", () => {

    document.querySelectorAll("[data-scene-i18n]").forEach(element => {
        element.dataset.itText = element.textContent;
    });

    const savedLanguage = localStorage.getItem("prismaLanguage") || "en";

    setLanguage(savedLanguage);

});