const translations = {

    en: {
        gallery: "Gallery",
        worlds: "Worlds",
        categories: "Categories",
        about: "About",
        contact: "Contact",
        exploreGallery: "EXPLORE GALLERY",
        heroEyebrow: "A GALLERY OF IMAGINED WORLDS",
        heroTitle: "PRISMA REALM",

       
	   heroText: "Light enters. Imagination emerges. Explore worlds beyond reality.",
	   exploreRealms: "EXPLORE THE REALMS",
worldsIntro: "Enter imagined worlds, each with its own landscapes, creatures, legends and stories.",
ardaWorld: "The World of Tolkien",
ardaEyebrow: "THE WORLD OF TOLKIEN",
ardaIntro: "Journey through the history of Arda, from the ancient days of the First Age to the twilight of the Third. Discover its peoples, kingdoms, heroes, creatures and legendary places.",
firstAge: "THE FIRST AGE",
firstAgeSubtitle: "The Elder Days — the beginning of the great history of Arda.",
firstAgeType: "The ancient kingdoms, heroes and wars of the Elder Days.",


eruIluvatar: "Eru Ilúvatar",
eruIluvatarDesc: "At the beginning there is Eru Ilúvatar, the Creator, origin of all that will be Arda.",
ainurSong: "The Song of the Ainur",
ainurSongDesc: "The Ainur perform the Great Music, from which the vision of the future world is born.",
ardaVision: "The Vision of Arda",
ardaVisionDesc: "The Music takes shape in the vision of Arda, the world destined to become reality.",
valarAgainstMelkor: "The Valar against Melkor",
valarAgainstMelkorDesc: "Melkor opposes the order of the other Ainur and becomes the first great force of discord.",
firstWar: "The First War",
firstWarDesc: "The Valar fight Melkor for dominion over Arda, reshaping the still-young world.",
valarDescent: "The Descent of the Valar",
valarDescentDesc: "The Valar enter Arda to shape it and prepare it for the coming of the Children of Ilúvatar.",
twoLamps: "The Two Lamps",
twoLampsDesc: "Illuin and Ormal illuminate Arda, bringing light to lands still without the Sun and the Moon.",
awakeningOfElves: "The Awakening of the Elves",
awakeningOfElvesDesc: "At Cuiviénen, the first Elves awaken, the Firstborn of Ilúvatar.",
eldar: "The Eldar",
eldarDesc: "Many Elves accept the invitation of the Valar and undertake the Great Journey westward.",
silmarilsCreation: "The Creation of the Silmarils",
silmarilsCreationDesc: "Fëanor forges the three Silmarils, capturing within them the light of the Two Trees of Valinor.",
deathOfFinwe: "The Death of Finwë",
deathOfFinweDesc: "Melkor returns to action, kills Finwë and takes the Silmarils from Fëanor's house.",
melkorUngoliant: "Melkor and Ungoliant",
melkorUngoliantDesc: "Melkor allies himself with Ungoliant, and together they bring about the death of the Two Trees of Valinor.",
silmarilsTheft: "The Theft of the Silmarils",
silmarilsTheftDesc: "After the death of Finwë, Melkor flees from Valinor carrying the Silmarils.",
feanorOath: "The Oath of Fëanor",
feanorOathDesc: "Fëanor and his sons swear to pursue anyone who possesses or takes the Silmarils.",
alqualonde: "The Kinslaying at Alqualondë",
alqualondeDesc: "The Noldor attack the Teleri to seize their ships. It is the first of the great kinslayings.",
judgmentOfMandos: "The Judgment of Mandos",
judgmentOfMandosDesc: "Mandos pronounces judgment upon the Noldor and the consequences of their rebellion.",
sunAndMoon: "The Sun and the Moon",
sunAndMoonDesc: "After the destruction of the Trees, the Sun and the Moon finally rise in the skies of Arda.",
helcaraxe: "Across the Helcaraxë",
helcaraxeDesc: "Fingolfin and his followers endure the terrible crossing of the Grinding Ice to reach Middle-earth.",
beleriand: "Beleriand",
beleriandDesc: "The Noldor arrive in Beleriand, and new Elven kingdoms arise, destined to become the heart of the First Age.",
morgothRegroups: "Morgoth Regroups",
morgothRegroupsDesc: "In the north, Morgoth rebuilds Angband and gathers the forces that will soon threaten all the kingdoms of Beleriand.",
dagorNuinGiliath: "The Dagor-nuin-Giliath",
dagorNuinGiliathDesc: "The Noldor face the armies of Morgoth in the first great battle after their return to Middle-earth.",
fallOfFingolfin: "The Fall of Fingolfin",
fallOfFingolfinDesc: "Fingolfin challenges Morgoth at the gates of Angband and fights the Dark Lord alone.",
berenMeetsLuthien: "Beren Meets Lúthien",
berenMeetsLuthienDesc: "In the forest of Doriath, Beren meets Lúthien, and one of the greatest love stories of Arda begins.",
silmaril: "The Silmaril",
silmarilDesc: "Beren tears a Silmaril from Morgoth's crown and fulfills the mission.",
berenCarcharoth: "Beren and Carcharoth",
berenCarcharothDesc: "Carcharoth swallows the Silmaril and flees through Doriath, pursued by Beren.",
silmarilRecovered: "The Silmaril Recovered",
silmarilRecoveredDesc: "The hunt for Carcharoth leads to the recovery of the Silmaril and the conclusion of the great quest of Beren and Lúthien.",
turinGlaurung: "Túrin and Glaurung",
turinGlaurungDesc: "Túrin's life becomes one of the darkest tragedies of the First Age, forever bound to the dragon Glaurung.",
fallOfNargothrond: "The Fall of Nargothrond",
fallOfNargothrondDesc: "Glaurung leads Morgoth's armies to the destruction of the great underground kingdom.",
fallOfGondolin: "The Fall of Gondolin",
fallOfGondolinDesc: "Turgon's hidden kingdom is discovered and destroyed by the forces of Morgoth.",
escapeFromGondolin: "The Escape from Gondolin",
escapeFromGondolinDesc: "Tuor, Idril and the survivors escape the ruined city and reach the mouths of the Sirion.",
earendilElwing: "Eärendil and Elwing",
earendilElwingDesc: "At the mouths of the Sirion, the fates of the last great kindreds of Elves and Men become intertwined.",
elwingReachesEarendil: "Elwing Reaches Eärendil",
elwingReachesEarendilDesc: "Elwing reaches Eärendil carrying the Silmaril, after the destruction of the havens of the Sirion.",
earendilJourney: "The Voyage of Eärendil",
earendilJourneyDesc: "Eärendil sails westward in search of the land of the Valar, carrying the Silmaril with him.",
earendilReachesAman: "Eärendil Reaches Aman",
earendilReachesAmanDesc: "After the long voyage across the western seas, Eärendil reaches the shores of Aman.",
pleaToValar: "The Plea to the Valar",
pleaToValarDesc: "Eärendil brings the Valar the plea for help from Elves and Men against Morgoth.",
vingilot: "Vingilot",
vingilotDesc: "Eärendil becomes the bearer of the Silmaril in the heavens, a symbol of hope for those who still fight against Morgoth.",
lastChildren: "The Last Children of the Great Kindreds",
lastChildrenDesc: "The events of the First Age leave a legacy destined to survive into the Ages that follow.",
finalConfrontationPreparation: "The Preparation for the Final Battle",
finalConfrontationPreparationDesc: "Morgoth gathers his remaining great forces to face the army of the Valar.",
morgothArmy: "Morgoth's Army",
morgothArmyDesc: "Orcs, Balrogs, dragons and other dark creatures are assembled for the decisive battle.",
warOfWrath: "The War of Wrath",
warOfWrathDesc: "The armies of the West arrive in Middle-earth, and the war that will end Morgoth's dominion begins.",
fallOfAncalagon: "The Fall of Ancalagon",
fallOfAncalagonDesc: "Eärendil confronts Ancalagon the Black in the skies, contributing to the final defeat of Morgoth's forces.",
captureOfMorgoth: "The Capture of Morgoth",
captureOfMorgothDesc: "After his defeat, Morgoth is captured by the forces of the Valar and stripped of his power.",
morgothDefeated: "Morgoth Defeated",
morgothDefeatedDesc: "The War of Wrath ends with the defeat of Morgoth and the fall of his dominion.",
morgothCrown: "The Crown of Morgoth",
morgothCrownDesc: "The crown that once held the Silmarils remains as a testament to the great fall of the Dark Lord.",
gatesOfVoid: "At the Gates of the Void",
gatesOfVoidDesc: "Morgoth is brought before the threshold beyond which he will be banished forever.",
morgothInVoid: "Morgoth in the Void",
morgothInVoidDesc: "Morgoth is cast beyond the Walls of the World, and his presence in Arda comes to an end.",
endOfBeleriand: "The End of Beleriand",
endOfBeleriandDesc: "The War of Wrath devastates the continent: much of Beleriand sinks beneath the sea, and the First Age comes to an end.",



secondAge: "THE SECOND AGE",


secondAge: "THE SECOND AGE",
secondAgeType: "The rise and fall of kingdoms, Númenor and the forging of the Rings.",
        secondAgeSubtitle: "The rise and fall of kingdoms, Númenor and the forging of the Rings.",
        saTitle1: "Lindon and the Grey Havens",
        saDesc1: "Lindon and the western havens of the Elves become the center of Elven presence in Middle-earth.",
        saTitle2: "Númenor",
        saDesc2: "The island of Númenor becomes the great homeland of the Edain, at the heart of the Second Age.",
        saTitle3: "The Expansion of Númenor",
        saDesc3: "The Númenóreans expand their influence along the coasts of Middle-earth.",
        saTitle4: "Sauron's Return to Middle-earth",
        saDesc4: "Sauron returns to Middle-earth and begins once again to gather power and servants.",
        saTitle5: "Eregion",
        saDesc5: "The Elves found Eregion near the Misty Mountains, turning it into a great center of craft and smithing.",
        saTitle6: "Annatar and Celebrimbor",
        saDesc6: "Sauron, in the guise of Annatar, presents himself to the Elves and gains Celebrimbor's trust.",
        saTitle7: "The Rings of Power",
        saDesc7: "The smiths of Eregion forge the Rings of Power under the influence of Annatar's teachings.",
        saTitle8: "The Elven Rings",
        saDesc8: "Celebrimbor and the Elven-smiths create the Three Rings, meant to preserve and protect what is beautiful in Middle-earth.",
        saTitle9: "The Giving of the Elven Rings",
        saDesc9: "The Three Rings are entrusted to the great Elven lords and kept beyond Sauron's direct influence.",
        saTitle10: "Sauron Forges the One",
        saDesc10: "Sauron forges the One Ring to dominate the other Rings of Power and their bearers.",
        saTitle11: "The Invasion of Eriador",
        saDesc11: "Sauron's armies invade Eriador and advance against the realms of the Elves.",
        saTitle12: "The End of Eregion",
        saDesc12: "Eregion is devastated and Celebrimbor is killed; the region forever loses its role as a great Elven center.",
        saTitle13: "Sauron Takes the Nine Rings",
        saDesc13: "Sauron takes possession of the Nine Rings destined for Men.",
        saTitle14: "Retreat to Mordor",
        saDesc14: "After the war, Sauron once again concentrates his power in the lands of Mordor.",
        saTitle15: "The Giving of the Nine",
        saDesc15: "Sauron gives the Nine Rings to powerful Men, who in time become the Nazgûl.",
        saTitle16: "Númenóreans Aid the Elves",
        saDesc16: "The great fleet of Númenor arrives in Middle-earth and forces Sauron to retreat.",
        saTitle17: "Númenórean Expansion",
        saDesc17: "The Númenóreans consolidate their presence along the coasts of Middle-earth and found new settlements.",
        saTitle18: "Sauron Conquers Some Settlements",
        saDesc18: "Sauron's influence grows in Middle-earth, threatening Númenórean dominions.",
        saTitle19: "Umbar",
        saDesc19: "Umbar becomes one of the great strongholds and naval bases of the Númenóreans in Middle-earth.",
        saTitle20: "Pelargir",
        saDesc20: "Pelargir is founded as a great haven of the Faithful Númenóreans on the banks of the Anduin.",
        saTitle21: "Ar-Pharazôn",
        saDesc21: "Ar-Pharazôn ascends the throne of Númenor and becomes the most powerful of the island's kings.",
        saTitle22: "Ar-Pharazôn Hears of Sauron",
        saDesc22: "Ar-Pharazôn learns of the growing threat of Sauron and decides to confront him.",
        saTitle23: "Ar-Pharazôn Prepares His Army",
        saDesc23: "The King of Númenor prepares a great army to subdue Sauron.",
        saTitle24: "Sauron and Ar-Pharazôn",
        saDesc24: "Ar-Pharazôn arrives in Middle-earth and Sauron realizes he cannot defeat him by force.",
        saTitle25: "Sauron Surrenders to Ar-Pharazôn",
        saDesc25: "Sauron willingly chooses to surrender and allows himself to be taken prisoner to Númenor.",
        saTitle26: "Sauron Is Taken to Númenor",
        saDesc26: "Sauron is brought to the island as a prisoner, but quickly begins to prepare his revenge.",
        saTitle27: "Sauron's Corruption",
        saDesc27: "Sauron gains Ar-Pharazôn's trust and begins to corrupt the court and society of Númenor.",
        saTitle28: "Ar-Pharazôn Against the Valar",
        saDesc28: "Sauron convinces Ar-Pharazôn that death is a deception and drives him against Aman.",
        saTitle29: "Tensions in Númenor",
        saDesc29: "The divide grows within Númenor between the Faithful to the Valar and those who desire greater power and dominion.",
        saTitle30: "Amandil's Decision",
        saDesc30: "Amandil, father of Elendil, decides to make a desperate voyage to Aman to ask the Valar for help.",
        saTitle31: "Elendil Prepares the Expedition",
        saDesc31: "Elendil prepares the ships of the Faithful to flee Númenor before its inevitable downfall.",
        saTitle32: "Amandil Sails for Aman",
        saDesc32: "Amandil sails west in an attempt to reach Aman and plead for the mercy of the Valar.",
        saTitle33: "Ar-Pharazôn Sails for Aman",
        saDesc33: "Ar-Pharazôn sails for Aman with the Great Armament to obtain immortality.",
        saTitle34: "Ar-Pharazôn on the Shores of Aman",
        saDesc34: "Ar-Pharazôn's fleet reaches the shores of Aman, crossing the forbidden boundary.",
        saTitle35: "Manwë Turns to Eru",
        saDesc35: "Faced with the rebellion of Men, Manwë calls upon Eru Ilúvatar and entrusts Arda's fate to him.",
        saTitle36: "Eru Removes Aman",
        saDesc36: "Eru intervenes in the history of Arda and changes its structure, removing Aman from the world.",
        saTitle37: "The Destruction of Númenor",
        saDesc37: "Númenor is drowned and destroyed; Elendil and the Faithful sail toward Middle-earth.",
        saTitle38: "Sauron Is Destroyed",
        saDesc38: "The destruction of Númenor destroys Sauron's body, but not his spirit: the One Ring remains with him.",
        saTitle39: "Sauron Returns to Mordor in Spirit",
        saDesc39: "Sauron returns to Mordor in spirit and regroups.",
        saTitle40: "Sauron's New Body",
        saDesc40: "In time, Sauron manages to rebuild a physical form, no longer able to regain his original appearance.",
        saTitle41: "Map of Elendil's Expedition",
        saDesc41: "The Faithful divide: Elendil sails north, while Isildur and Anárion sail south toward the Anduin.",
        saTitle42: "The Men of the Mountains",
        saDesc42: "The Faithful divide: Elendil sails north, while Isildur and Anárion sail south toward the Anduin.",
        saTitle43: "The Founding of Arnor",
        saDesc43: "Elendil founds Arnor in the north and establishes the realm of the northern Dúnedain.",
        saTitle44: "The Founding of Gondor",
        saDesc44: "Isildur and Anárion found Gondor in the south.",
        saTitle45: "The Oath to Isildur",
        saDesc45: "The King of the Men of the Mountains swears allegiance to Isildur at the Stone of Erech.",
        saTitle46: "Gil-galad and Elendil Against Sauron",
        saDesc46: "Gil-galad and Elendil face Sauron directly in the final confrontation.",
        saTitle47: "Sauron Conquers Minas Ithil",
        saDesc47: "Sauron attacks Gondor and captures Minas Ithil, later renamed Minas Morgul.",
        saTitle48: "Isildur's Curse",
        saDesc48: "Sauron attacks Gondor and captures Minas Ithil, later renamed Minas Morgul.",
        saTitle49: "The Alliance at Imladris",
        saDesc49: "Elves and Dúnedain join the Last Alliance, while the allied forces gather at Imladris.",
        saTitle50: "The Battle of Dagorlad",
        saDesc50: "The Last Alliance faces Sauron's forces in the great Battle of Dagorlad and wins.",
        saTitle51: "The Alliance Marches to Barad-dûr",
        saDesc51: "The army of the Last Alliance crosses Middle-earth and marches toward Mordor.",
        saTitle52: "The Siege of Barad-dûr",
        saDesc52: "After the victory at Dagorlad, the forces of the Alliance enter Mordor and besiege Barad-dûr for seven years.",
        saTitle53: "Sauron Against Gil-galad and Elendil",
        saDesc53: "In the final confrontation, Sauron faces Gil-galad and Elendil and kills both Kings.",
        saTitle54: "Isildur Defeats Sauron",
        saDesc54: "Isildur cuts the Ring from Sauron's hand with the shard of Narsil's hilt and takes the One Ring.",
        saTitle55: "The Destruction of Sauron",
        saDesc55: "Separated from the One Ring, Sauron loses the Ring's power and his body is destroyed.",
        saTitle56: "Isildur and the One Ring",
        saDesc56: "Isildur remains in possession of the One Ring as the Second Age comes to an end.",
thirdAge: "THE THIRD AGE",
thirdAgeType: "The age of the great kingdoms and the War of the Ring.",
ardaCharacters: "CHARACTERS",
ardaCharactersType: "Heroes, kings, elves, warriors, creatures and legendary figures.",
ardaPlaces: "PLACES",
ardaPlacesType: "Kingdoms, cities, forests, mountains and forgotten lands.",
ardaCreatures: "CREATURES",
ardaCreaturesType: "Beasts, monsters and beings that inhabit the world of Arda.",
eternalKingdoms: "THE ETERNAL KINGDOMS",
eternalKingdomsType: "Realms of kings, castles and ancient powers",
wildlands: "THE WILDLANDS",
wildlandsType: "Untamed landscapes and forgotten places",
darkRealms: "THE DARK REALMS",
darkRealmsType: "Shadowed lands, ruins and forbidden kingdoms",
celestialRealms: "THE CELESTIAL REALMS",
celestialRealmsType: "Worlds beyond the boundaries of reality",
forgottenLands: "THE FORGOTTEN LANDS",
forgottenLandsType: "Lost civilizations and mysteries of the past",
	   
latestArtworks: "LATEST ARTWORKS",
lostValley: "THE LOST VALLEY",
dragonOfAsh: "DRAGON OF ASH",
dragonType: "Fantasy · Creature",
citadelInClouds: "CITADEL IN THE CLOUDS",
citadelType: "Fantasy · Environment",
landscapes: "LANDSCAPES",
landscapesType: "Places and horizons",
ancientForest: "ANCIENT FOREST",
landscapeType: "Fantasy · Landscape",
fallenKing: "THE FALLEN KING",
fallenKingType: "Dark Fantasy · Character",
shatteredRealm: "SHATTERED REALM",
shatteredRealmType: "Dark Fantasy · Environment",
fantasy: "FANTASY",
fantasyType: "Epic worlds and legends",
creatures: "CREATURES",
creaturesType: "Beasts and beings",
worlds: "WORLDS",
worldsType: "Realms and dimensions",
characters: "CHARACTERS",
charactersType: "Heroes and villains",
darkFantasy: "DARK FANTASY",
darkFantasyType: "Shadows and corruption",
exploreCategories: "EXPLORE CATEGORIES",
whereImaginationTakesForm: "WHERE IMAGINATION TAKES FORM",
navigation: "NAVIGATION",
info: "INFO",
termsOfUse: "Terms of Use",
privacyPolicy: "Privacy Policy",
cookiesPolicy: "Cookies Policy",
stayUpdated: "STAY UPDATED",
newArtworks: "New artworks, behind the scenes and exclusive content.",
emailPlaceholder: "Your email address"
	},

    it: {
        gallery: "Galleria",
        worlds: "Mondi",
        categories: "Categorie",
        about: "Chi siamo",
        contact: "Contatti",
        exploreGallery: "ESPLORA LA GALLERIA",
        heroEyebrow: "UNA GALLERIA DI MONDI IMMAGINARI",
        heroTitle: "PRISMA REALM",

        heroText: "La luce entra. L'immaginazione emerge. Esplora mondi oltre la realtà.",
exploreRealms: "ESPLORA I REGNI",
worldsIntro: "Entra in mondi immaginari, ognuno con i propri paesaggi, creature, leggende e storie.",
ardaWorld: "Il Mondo di Tolkien",
ardaEyebrow: "IL MONDO DI TOLKIEN",
ardaIntro: "Viaggia attraverso la storia di Arda, dagli antichi giorni della Prima Era fino al crepuscolo della Terza. Scopri i suoi popoli, regni, eroi, creature e luoghi leggendari.",
firstAge: "LA PRIMA ERA",
firstAgeSubtitle: "I Giorni Antichi — l'inizio della grande storia di Arda.",
firstAgeType: "Gli antichi regni, gli eroi e le guerre dei Giorni Antichi.",

eruIluvatar: "Eru Ilúvatar",
eruIluvatarDesc: "All'inizio esiste Eru Ilúvatar, il Creatore, origine di tutto ciò che sarà Arda.",
ainurSong: "Il Canto degli Ainur",
ainurSongDesc: "Gli Ainur intonano la Grande Musica, dalla quale nasce la visione del mondo futuro.",
ardaVision: "La visione di Arda",
ardaVisionDesc: "La Musica prende forma nella visione di Arda, il mondo destinato a diventare realtà.",
valarAgainstMelkor: "I Valar contro Melkor",
valarAgainstMelkorDesc: "Melkor si oppone all'ordine degli altri Ainur e diventa la prima grande forza di discordia.",
firstWar: "La prima guerra",
firstWarDesc: "I Valar combattono Melkor per il dominio di Arda, sconvolgendo il mondo ancora giovane.",
valarDescent: "La discesa dei Valar",
valarDescentDesc: "I Valar entrano in Arda per plasmarla e prepararla alla venuta dei Figli di Ilúvatar.",
twoLamps: "Le Due Lampade",
twoLampsDesc: "Illuin e Ormal illuminano Arda, portando luce nelle terre ancora prive del Sole e della Luna.",
awakeningOfElves: "Il risveglio degli Elfi",
awakeningOfElvesDesc: "A Cuiviénen si risvegliano i primi Elfi, i Primogeniti di Ilúvatar.",
eldar: "Gli Eldar",
eldarDesc: "Molti Elfi accettano l'invito dei Valar e intraprendono la Grande Marcia verso Occidente.",
silmarilsCreation: "La creazione dei Silmaril",
silmarilsCreationDesc: "Fëanor forgia i tre Silmaril, racchiudendo in essi la luce dei Due Alberi di Valinor.",
deathOfFinwe: "La morte di Finwë",
deathOfFinweDesc: "Melkor torna in azione, uccide Finwë e sottrae i Silmaril dalla casa di Fëanor.",
melkorUngoliant: "Melkor e Ungoliant",
melkorUngoliantDesc: "Melkor si allea con Ungoliant, che insieme causano la morte dei Due Alberi di Valinor.",
silmarilsTheft: "Il furto dei Silmaril",
silmarilsTheftDesc: "Dopo la morte di Finwë, Melkor fugge da Valinor portando con sé i Silmaril.",
feanorOath: "Il Giuramento di Fëanor",
feanorOathDesc: "Fëanor e i suoi figli giurano di perseguire chiunque possieda o sottragga i Silmaril.",
alqualonde: "La strage di Alqualondë",
alqualondeDesc: "I Noldor attaccano i Teleri per impossessarsi delle loro navi. È il primo dei grandi massacri fratricidi.",
judgmentOfMandos: "Il Giudizio di Mandos",
judgmentOfMandosDesc: "Mandos pronuncia il giudizio sui Noldor e sulle conseguenze della loro ribellione.",
sunAndMoon: "Il Sole e la Luna",
sunAndMoonDesc: "Dopo la distruzione degli Alberi, il Sole e la Luna sorgono finalmente nei cieli di Arda.", 
helcaraxe: "Attraverso il Helcaraxë",
helcaraxeDesc: "Fingolfin e i suoi seguaci affrontano il terribile passaggio del Ghiaccio Macinatore per raggiungere la Terra di Mezzo.",
beleriand: "Il Beleriand",
beleriandDesc: "I Noldor giungono nel Beleriand e sorgono nuovi regni elfici destinati a diventare il cuore della Prima Era.",
morgothRegroups: "Morgoth si riorganizza",
morgothRegroupsDesc: "Nel nord, Morgoth ricostruisce Angband e raduna le forze che presto minacceranno tutti i regni del Beleriand.",
dagorNuinGiliath: "La Dagor-nuin-Giliath",
dagorNuinGiliathDesc: "I Noldor affrontano gli eserciti di Morgoth nella prima grande battaglia dopo il loro ritorno nella Terra di Mezzo.",
fallOfFingolfin: "La caduta di Fingolfin",
fallOfFingolfinDesc: "Fingolfin sfida Morgoth alle porte di Angband e combatte da solo contro il Signore Oscuro.",
berenMeetsLuthien: "Beren incontra Lúthien",
berenMeetsLuthienDesc: "Nella foresta di Doriath, Beren incontra Lúthien e ha inizio una delle più grandi storie d'amore di Arda.",
silmaril: "Il Silmaril",
silmarilDesc: "Beren strappa un Silmaril dalla corona di Morgoth e porta a compimento la missione.",
berenCarcharoth: "Beren e Carcharoth",
berenCarcharothDesc: "Carcharoth inghiotte il Silmaril e fugge attraverso Doriath, inseguito da Beren.",
silmarilRecovered: "Il Silmaril recuperato",
silmarilRecoveredDesc: "La caccia a Carcharoth conduce alla riconquista del Silmaril e alla conclusione della grande impresa di Beren e Lúthien.",
turinGlaurung: "Túrin e Glaurung",
turinGlaurungDesc: "La vita di Túrin diventa una delle più oscure tragedie della Prima Era, legata indissolubilmente al drago Glaurung.",
fallOfNargothrond: "La caduta di Nargothrond",
fallOfNargothrondDesc: "Glaurung conduce gli eserciti di Morgoth alla distruzione del grande regno sotterraneo.",
fallOfGondolin: "La caduta di Gondolin",
fallOfGondolinDesc: "Il regno nascosto di Turgon viene scoperto e distrutto dalle forze di Morgoth.",
escapeFromGondolin: "La fuga da Gondolin",
escapeFromGondolinDesc: "Tuor, Idril e i superstiti riescono a fuggire dalla città in rovina e a raggiungere le foci del Sirion.",
earendilElwing: "Eärendil ed Elwing",
earendilElwingDesc: "Alle foci del Sirion si intrecciano le vicende delle ultime grandi stirpi degli Elfi e degli Uomini.",
elwingReachesEarendil: "Elwing raggiunge Eärendil",
elwingReachesEarendilDesc: "Elwing raggiunge Eärendil portando il Silmaril, dopo la distruzione dei rifugi del Sirion.", 
earendilJourney: "Il viaggio di Eärendil",
earendilJourneyDesc: "Eärendil naviga verso Occidente alla ricerca della terra dei Valar, portando con sé il Silmaril.",
earendilReachesAman: "Eärendil raggiunge Aman",
earendilReachesAmanDesc: "Dopo il lungo viaggio attraverso i mari dell'Occidente, Eärendil raggiunge le coste di Aman.",
pleaToValar: "La supplica ai Valar",
pleaToValarDesc: "Eärendil porta ai Valar la richiesta di aiuto degli Elfi e degli Uomini contro Morgoth.",
vingilot: "Vingilot",
vingilotDesc: "Eärendil diventa il portatore del Silmaril nei cieli, simbolo di speranza per coloro che ancora combattono contro Morgoth.",
lastChildren: "Gli ultimi figli delle grandi stirpi",
lastChildrenDesc: "Le vicende della Prima Era lasciano un'eredità destinata a sopravvivere nelle Ere successive.",
finalConfrontationPreparation: "La preparazione dello scontro finale",
finalConfrontationPreparationDesc: "Morgoth raccoglie le sue ultime grandi forze per affrontare l'esercito dei Valar.",
morgothArmy: "L'esercito di Morgoth",
morgothArmyDesc: "Orchi, Balrog, draghi e altre creature oscure vengono schierati per la battaglia decisiva.",
warOfWrath: "La Guerra dell'Ira",
warOfWrathDesc: "Gli eserciti dell'Occidente giungono nella Terra di Mezzo e ha inizio la guerra che porrà fine al dominio di Morgoth.",
fallOfAncalagon: "La caduta di Ancalagon",
fallOfAncalagonDesc: "Eärendil affronta Ancalagon il Nero nei cieli e contribuisce alla definitiva sconfitta delle forze di Morgoth.",
captureOfMorgoth: "La cattura di Morgoth",
captureOfMorgothDesc: "Dopo la sconfitta, Morgoth viene catturato dalle forze dei Valar e privato del suo potere.",
morgothDefeated: "Morgoth sconfitto",
morgothDefeatedDesc: "La Guerra dell'Ira termina con la sconfitta di Morgoth e la caduta del suo dominio.",
morgothCrown: "La corona di Morgoth",
morgothCrownDesc: "La corona che aveva contenuto i Silmaril rimane come testimonianza della grande caduta del Signore Oscuro.",
gatesOfVoid: "Alle porte del Vuoto",
gatesOfVoidDesc: "Morgoth viene condotto davanti alla soglia oltre la quale sarà bandito per sempre.",
morgothInVoid: "Morgoth nel Vuoto",
morgothInVoidDesc: "Morgoth viene espulso oltre le mura del mondo e la sua presenza in Arda giunge alla fine.",
endOfBeleriand: "La fine del Beleriand",
endOfBeleriandDesc: "La Guerra dell'Ira sconvolge il continente: gran parte del Beleriand sprofonda nelle acque e la Prima Era giunge al termine.",
  
  
secondAge: "LA SECONDA ERA",

 
secondAgeType: "L'ascesa e la caduta dei regni, Númenor e la forgiatura degli Anelli.",
        secondAgeSubtitle: "L'ascesa e la caduta dei regni, Númenor e la forgiatura degli Anelli.",
        saTitle1: "Lindon e i Porti Grigi",
        saDesc1: "Lindon e i porti occidentali degli Elfi diventano il centro della presenza elfica nella Terra di Mezzo.",
        saTitle2: "Númenor",
        saDesc2: "L'isola di Númenor diventa la grande patria degli Edain, al centro della storia della Seconda Era.",
        saTitle3: "Espansione di Númenor",
        saDesc3: "I Númenóreani iniziano a esplorare e frequentare le coste della Terra di Mezzo, ampliando la loro influenza.",
        saTitle4: "Il ritorno di Sauron nella Terra di Mezzo",
        saDesc4: "Sauron torna nella Terra di Mezzo e comincia nuovamente a radunare potere e servitori.",
        saTitle5: "Eregion",
        saDesc5: "Gli Elfi fondano Eregion presso le Montagne Nebbiose, trasformandola in un grande centro di arti e forgiatura.",
        saTitle6: "Annatar e Celebrimbor",
        saDesc6: "Sauron, sotto le sembianze di Annatar, si presenta agli Elfi e conquista la fiducia di Celebrimbor.",
        saTitle7: "Gli Anelli del Potere",
        saDesc7: "Gli artigiani di Eregion forgiano gli Anelli del Potere sotto l'influenza degli insegnamenti di Annatar.",
        saTitle8: "Gli Anelli Elfici",
        saDesc8: "Celebrimbor e i fabbri elfici realizzano i Tre Anelli, destinati a preservare e proteggere ciò che è bello nella Terra di Mezzo.",
        saTitle9: "La consegna degli Anelli Elfici",
        saDesc9: "I Tre Anelli vengono affidati ai grandi signori elfici e sottratti all'influenza diretta di Sauron.",
        saTitle10: "Sauron forgia l'Unico",
        saDesc10: "Sauron forgia l'Unico Anello per dominare gli altri Anelli del Potere e i loro portatori.",
        saTitle11: "Invasione nell'Eriador",
        saDesc11: "Gli eserciti di Sauron invadono l'Eriador e avanzano contro i domini degli Elfi.",
        saTitle12: "Fine dell'Eregion",
        saDesc12: "Eregion viene devastata e Celebrimbor viene ucciso; la regione perde per sempre il suo ruolo di grande centro elfico.",
        saTitle13: "Sauron si impossessa dei Nove Anelli",
        saDesc13: "Sauron entra in possesso dei Nove Anelli destinati agli Uomini.",
        saTitle14: "Ritirata a Mordor",
        saDesc14: "Dopo la guerra, Sauron concentra nuovamente il proprio potere nelle terre di Mordor.",
        saTitle15: "La consegna dei Nove",
        saDesc15: "I Nove Anelli vengono consegnati da Sauron a uomini potenti, che nel tempo diventeranno i Nazgûl.",
        saTitle16: "Númenóreani in soccorso degli Elfi",
        saDesc16: "La grande flotta di Númenor giunge nella Terra di Mezzo e costringe Sauron a ritirarsi.",
        saTitle17: "Espansioni Númenóreane",
        saDesc17: "I Númenóreani consolidano la loro presenza sulle coste della Terra di Mezzo e fondano nuovi insediamenti.",
        saTitle18: "Sauron conquista acuni insediamenti",
        saDesc18: "L'influenza di Sauron cresce nella Terra di Mezzo minacciando i domini númenóreani.",
        saTitle19: "Umbar",
        saDesc19: "Umbar diventa una delle grandi fortezze e basi navali dei Númenóreani nella Terra di Mezzo.",
        saTitle20: "Pelargir",
        saDesc20: "Pelargir viene fondata come grande porto dei Númenóreani Fedeli sulle rive dell'Anduin.",
        saTitle21: "Ar-Pharazôn",
        saDesc21: "Ar-Pharazôn sale al trono di Númenor e diventa il più potente dei re dell'isola.",
        saTitle22: "Ar-Pharazôn viene a sapere di Sauron",
        saDesc22: "Ar-Pharazôn apprende della crescente minaccia di Sauron e decide di affrontarlo",
        saTitle23: "Ar-Pharazôn prepara la sua armata",
        saDesc23: "Il re di Númenor prepara una grande armata per sottomettere Sauron.",
        saTitle24: "Sauron e Ar-Pharazôn",
        saDesc24: "Ar-Pharazôn giunge nella Terra di Mezzo e Sauron comprende di non poterlo sconfiggere con la forza.",
        saTitle25: "Sauron si consegna ad Ar-Pharazôn",
        saDesc25: "Sauron sceglie di arrendersi volontariamente e si lascia condurre prigioniero a Númenor.",
        saTitle26: "Sauron viene portato a Númenor",
        saDesc26: "Sauron viene condotto nell'isola come prigioniero, ma prepara rapidamente la propria vendetta.",
        saTitle27: "La corruzione di Sauron",
        saDesc27: "Sauron conquista la fiducia di Ar-Pharazôn e inizia a corrompere la corte e la società di Númenor.",
        saTitle28: "Ar-Pharazôn contro i Valar",
        saDesc28: "Sauron convince Ar-Pharazôn che la morte è un inganno e lo spinge contro Aman.",
        saTitle29: "Tensioni a Númenór",
        saDesc29: "Nella società di Númenor cresce la frattura tra i Fedeli ai Valar e coloro che desiderano maggiore potere e dominio.",
        saTitle30: "la decisione di amandil",
        saDesc30: "Amandil, padre di Elendil, decide di tentare una disperata navigazione verso Aman per chiedere aiuto ai Valar.",
        saTitle31: "Elendil prepara la spedizione",
        saDesc31: "Elendil prepara le navi dei Fedeli per fuggire da Númenor prima della sua inevitabile rovina.",
        saTitle32: "Amandil parte per Aman",
        saDesc32: "Amandil salpa verso occidente nel tentativo di raggiungere Aman e implorare la misericordia dei Valar.",
        saTitle33: "Ar-Pharazôn parte per Aman",
        saDesc33: "Ar-Pharazôn salpa con la Grande Armata per Aman per ottenere l'immortalità.",
        saTitle34: "Ar-Pharazôn sulle rive di Aman",
        saDesc34: "La flotta di Ar-Pharazôn raggiunge le rive di Aman, oltrepassando il limite imposto.",
        saTitle35: "Manwë si rivolge a Eru",
        saDesc35: "Di fronte alla ribellione degli Uomini, Manwë invoca Eru Ilúvatar e affida a lui il destino di Arda.",
        saTitle36: "Eru estrapola Aman",
        saDesc36: "Eru interviene nella storia di Arda e ne muta la struttura, separando Aman dal mondo.",
        saTitle37: "Distruzione di Númenor",
        saDesc37: "Númenor viene sommersa e distrutta; Elendil e i Fedeli viaggiano verso la Terra di Mezzo.",
        saTitle38: "Sauron viene distrutto",
        saDesc38: "La distruzione di Númenor annienta il corpo di Sauron, ma non il suo spirito: l’Unico Anello rimane con lui.",
        saTitle39: "Sauron in spirito torna a Mordor",
        saDesc39: "sauron torna a mordor in spirito e si riorganizza.",
        saTitle40: "il corpo di sauron",
        saDesc40: "Sauron riesce nel tempo a ricostituire una forma fisica fittizia, non riavendo più il suo aspetto originario.",
        saTitle41: "Mappa spedizione Elendil",
        saDesc41: "La spedizione dei Fedeli si divide: Elendil raggiunge il nord, mentre Isildur e Anárion navigano verso il sud e l'Anduin.",
        saTitle42: "Gli Uomini delle Montagne",
        saDesc42: "Gli Uomini delle Montagne riconoscono il potere di Sauron e gli prestano servizio.",
        saTitle43: "Costruzione di Arnor",
        saDesc43: "Elendil fonda Arnor nel nord e stabilisce il regno dei Dúnedain settentrionali.",
        saTitle44: "Costruzione di Gondor",
        saDesc44: "Isildur e Anárion fondano Gondor nel sud, dando vita al grande regno dei Dúnedain della Terra di Mezzo.",
        saTitle45: "Giuramento a Isildur",
        saDesc45: "Il re degli Uomini delle Montagne giura fedeltà a Isildur presso la Pietra di Erech.",
        saTitle46: "Gil-galad ed Elendil contro Sauron",
        saDesc46: "Alla fine dell'assedio, Gil-galad ed Elendil affrontano direttamente Sauron alle pendici di Orodruin.",
        saTitle47: "Sauron conquista Minas Ithil",
        saDesc47: "Sauron attacca Gondor e conquista Minas Ithil, che diventa Minas Morgul molti anni dopo.",
        saTitle48: "l'anatema di Isildur",
        saDesc48: "Gli Uomini delle Montagne infrangono il giuramento; non troveranno pace fino a giuramento onorato.",
        saTitle49: "Alleanza a Imladris",
        saDesc49: "Elfi e Dúnedain si uniscono nella Last Alliance, mentre le forze alleate si concentrano a Imladris.",
        saTitle50: "Battaglia di Dagorlad",
        saDesc50: "La Last Alliance affronta le forze di Sauron nella grande Battaglia di Dagorlad e ottiene la vittoria.",
        saTitle51: "Alleanza marcia verso Barad-Dûr",
        saDesc51: "L'esercito della Last Alliance attraversa la Terra di Mezzo e marcia verso Mordor.",
        saTitle52: "Assedio a Barad-Dûr",
        saDesc52: "Dopo la vittoria a Dagorlad, le forze dell'Alleanza entrano in Mordor e assediano Barad-dûr per sette anni.",
        saTitle53: "Sauron contro Gil-galad ed Elendil",
        saDesc53: "Nel confronto finale, Sauron affronta Gil-galad ed Elendil e uccide entrambi i Re.",
        saTitle54: "Isildur sconfigge Sauron",
        saDesc54: "Isildur recide il dito di Sauron con il frammento dell'elsa di Narsil e prende l'Unico.",
        saTitle55: "Distruzione di Sauron",
        saDesc55: "Separato dall'Unico, Sauron perde il potere dell'Anello e il suo corpo viene distrutto.",
        saTitle56: "Isildur e l'Unico",
        saDesc56: "Isildur rimane in possesso dell'Unico Anello, mentre la Seconda Era giunge al termine.",
thirdAge: "LA TERZA ERA",
thirdAgeType: "L'epoca dei grandi regni e della Guerra dell'Anello.",
ardaCharacters: "PERSONAGGI",
ardaCharactersType: "Eroi, re, elfi, guerrieri, creature e figure leggendarie.",
ardaPlaces: "LUOGHI",
ardaPlacesType: "Regni, città, foreste, montagne e terre dimenticate.",
ardaCreatures: "CREATURE",
ardaCreaturesType: "Bestie, mostri ed esseri che abitano il mondo di Arda.",
eternalKingdoms: "I REGNI ETERNI",
eternalKingdomsType: "Regni di re, castelli e antichi poteri",
wildlands: "LE TERRE SELVAGGE",
wildlandsType: "Paesaggi incontaminati e luoghi dimenticati",
darkRealms: "I REGNI OSCURI",
darkRealmsType: "Terre nell'ombra, rovine e regni proibiti",
celestialRealms: "I REGNI CELESTIALI",
celestialRealmsType: "Mondi oltre i confini della realtà",
forgottenLands: "LE TERRE DIMENTICATE",
forgottenLandsType: "Civiltà perdute e misteri del passato",
latestArtworks: "ULTIME OPERE",
lostValley: "LA VALLE PERDUTA",
dragonOfAsh: "DRAGO DI CENERE",
dragonType: "Fantasy · Creatura",
citadelInClouds: "CITTÀ DELLE NUVOLE",
citadelType: "Fantasy · Ambientazione",
landscapes: "PAESAGGI",
landscapesType: "Luoghi e orizzonti",
ancientForest: "FORESTA ANTICA",
landscapeType: "Fantasy · Paesaggio",
fallenKing: "IL RE CADUTO",
fallenKingType: "Dark Fantasy · Personaggio",
shatteredRealm: "REGNO FRANTUMATO",
shatteredRealmType: "Dark Fantasy · Ambientazione",
fantasy: "FANTASY",
fantasyType: "Mondi epici e leggende",
creatures: "CREATURE",
creaturesType: "Bestie ed esseri",
worlds: "MONDI",
worldsType: "Regni e dimensioni",
characters: "PERSONAGGI",
charactersType: "Eroi e malvagi",
darkFantasy: "DARK FANTASY",
darkFantasyType: "Ombre e corruzione",
exploreCategories: "ESPLORA CATEGORIE",
whereImaginationTakesForm: "DOVE L'IMMAGINAZIONE PRENDE FORMA",
navigation: "NAVIGAZIONE",
info: "INFO",
termsOfUse: "Termini di utilizzo",
privacyPolicy: "Informativa sulla privacy",
cookiesPolicy: "Politica sui cookie",
stayUpdated: "RESTA AGGIORNATO",
newArtworks: "Nuove opere, dietro le quinte e contenuti esclusivi.",
emailPlaceholder: "Il tuo indirizzo email"
	}

};


function setLanguage(lang) {

    const languageButton = document.getElementById("language-toggle");

    if (languageButton) {
        languageButton.textContent = lang.toUpperCase();
    }

    document.querySelectorAll("[data-i18n]").forEach(element => {

        const key = element.getAttribute("data-i18n");

        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }

    });

    document.documentElement.classList.add("language-ready");

    localStorage.setItem("prismaLanguage", lang);
}


function toggleLanguage() {
    const currentLanguage = localStorage.getItem("prismaLanguage") || "en";
    setLanguage(currentLanguage === "en" ? "it" : "en");
}


document.addEventListener("DOMContentLoaded", () => {

    const savedLanguage = localStorage.getItem("prismaLanguage") || "en";

    setLanguage(savedLanguage);


});